const assert=require('node:assert/strict'),fs=require('node:fs');const cards=require('../dist/cards.json');const {Game,clone}=require('../dist/engine.js');require('../dist/effects.js');require('../dist/decks.js');const proto={combat:Game.prototype.combat,checkWin:Game.prototype.checkWin,stats:Game.prototype.stats};const D=require('../dist/campaign-data.js'),A=(require('../dist/campaign-deck.js'),require('../dist/campaign-engine.js'));const {simulate,runStage,applyEvent}=require('./campaign-simulation.cjs');let count=0;
function test(name,fn){try{fn();console.log('PASS',name);count++;}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
function profile(stage=0,scene=0){const p=A.fresh();p.stage=stage;p.scene=scene;if(stage){p.roster=['slark','slardar','magnus','enchantress','bounty_hunter'];p.party=[...p.roster];for(const k of p.roster)p.loyalty[k]=3;p.growth={attack:stage*.5,health:stage};}return p;}
function game(stage=0,scene=0){const g=new A.CampaignGame(cards);g.begin(profile(stage,scene),123);return g;}
function hand(g,k){g.s.players[0].hand.push({uid:g.id(),k,lock:0});g.s.lanes[g.s.lane].mana[0]=20;}
test('Classic catalog and prototype methods are untouched',()=>{assert.equal(cards.filter(c=>!c.expansion).length,303);for(const k in proto)assert.equal(Game.prototype[k],proto[k]);const g=new Game(cards);g.newGame(ARTIFACT_DECKS[0],ARTIFACT_DECKS[1],77);assert.equal(g.s.lanes.length,3);assert.equal(g.card('slark'),undefined);g.towerDamage(1,0,40);g.checkWin();assert.equal(g.s.lanes[0].towers[1].hp,80);assert.equal(g.s.winner,null);});
test('mandatory Slark, unique roster and at most five heroes',()=>{const p=profile(5);assert(A.valid(p));assert.throws(()=>A.chooseParty(p,'slark'));p.roster.push('tiny');p.loyalty.tiny=2;assert.throws(()=>A.chooseParty(p,'tiny'));A.chooseParty(p,'magnus');A.chooseParty(p,'tiny');assert.equal(p.party.length,5);p.party[0]='tiny';assert(!A.valid(p));});
test('save validation rejects broken or incompatible payloads',()=>{for(const change of [p=>p.version=9,p=>p.gold=NaN,p=>p.deck=['invalid'],p=>p.weapon='invalid',p=>p.battle={chapter:0}]){const p=A.fresh();change(p);assert(!A.valid(p));}});
test('one/two/three fronts contain no units or actions in inactive lanes',()=>{for(const [n,sc]of[[0,0],[2,0],[14,1]]){const g=game(n,sc),lanes=D.scene(D.stages[n],sc).lanes;assert.equal(g.s.activeLanes,lanes);assert(g.all().every(u=>u.lane<lanes));for(let l=0;l<lanes;l++)g.combat();if(g.s.winner===null){assert.equal(g.s.round,2);assert.equal(g.s.lane,0);assert.equal(g.s.phase,'action');}assert(!g.s.log.some(e=>e.type==='lane'&&e.lane>=lanes));}});
test('initial hero assignments and once-per-round movement preserve unique positions',()=>{const p=profile(2);p.placements=Object.fromEntries(p.party.map(k=>[k,1]));const g=new A.CampaignGame(cards);g.begin(p);assert.equal(g.all(0,1).filter(u=>u.hero).length,5);assert.equal(new Set(g.all(0,1).map(u=>u.pos)).size,5);g.relocate(g.all(0,1)[0].uid,0);assert.throws(()=>g.relocate(g.all(0,1)[0].uid,0));});
test('party wipe loses even with surviving summoned units and no tower damage',()=>{const g=game();g.spawnAlly(0);for(const u of g.all(0).filter(u=>u.hero))g.damage(u,999,true);g.sweep();assert.equal(g.s.winner,1);assert(g.all(0).some(u=>!u.hero));});
test('simultaneous last hero and last enemy death is defeat, not victory',()=>{const g=game();for(const u of g.all())g.damage(u,999,true);g.sweep();assert.equal(g.s.winner,1);});
test('elimination ignores tower damage, assault requires every seal',()=>{const g=game();g.towerDamage(0,0,999);g.checkWin();assert.equal(g.s.winner,null);const a=game(14,1);for(let l=0;l<2;l++)a.towerDamage(1,l,999);a.checkWin();assert.equal(a.s.winner,null);a.towerDamage(1,2,999);a.checkWin();assert.equal(a.s.winner,0);});
test('defense victory checks waves and loss checks every friendly core',()=>{const g=game(2,1);g.s.round=4;g.s.lane=1;g.combat();assert.equal(g.s.winner,0);const p=profile(2,1);p.battle=g.s;assert(A.valid(p),'ended defense save must reload');const h=game(2,1);h.towerDamage(0,1,999);h.checkWin();assert.equal(h.s.winner,1);});
test('invalid target cannot spend mana or remove a card; equipment is hero only',()=>{const g=game();hand(g,'story_blade');const before=clone(g.s);assert.throws(()=>g.cast('story_blade',g.all(1)[0].uid));assert.deepEqual(g.s,before);const u=g.spawnAlly(0);assert.throws(()=>g.cast('story_blade',u.uid));const hero=g.all(0).find(u=>u.hero);g.cast('story_blade',hero.uid);assert.equal(hero.items.Weapon.k,'short_sword');});
test('healing, armor and direct damage use existing shared rules',()=>{const g=game(),u=g.all(0)[0],e=g.all(1)[0];g.damage(u,9,true);hand(g,'story_salve');g.cast('story_salve',u.uid);assert.equal(u.damage,3);hand(g,'story_essence');g.cast('story_essence',e.uid);assert.equal(e.damage,5);assert.equal(g.stats(u).attack,6);});
test('stealth has no automatic outgoing damage and two loud casts lose',()=>{const g=game(10,1),e=g.all(1)[0],forecast=g.combatForecast();assert.equal(forecast.units[e.uid].damage,0);hand(g,'story_pounce');g.cast('story_pounce',e.uid);assert.equal(g.s.alarm,1);hand(g,'story_essence');g.cast('story_essence',e.uid);assert.equal(g.s.winner,1);});
test('time puzzle cannot win before casting rewind',()=>{const g=game(13);for(const e of g.all(1))g.damage(e,999,true);g.sweep();assert.equal(g.s.winner,null);hand(g,'story_rewind');g.cast('story_rewind',g.all(0)[0].uid);assert.equal(g.s.winner,0);});
test('discard recycling never deals dead heroes or creeps as cards',()=>{const g=game();g.s.players[0].hand=[];g.s.players[0].deck=[];g.s.players[0].discard=['melee_creep','slark','story_guard'];g.drawCards(3);assert.deepEqual(g.s.players[0].hand.map(h=>h.k),['story_guard']);});
test('rewards are once only, recruit enemies, persist growth and restore at camp',()=>{const p=A.fresh(),r=runStage(p,123);assert.equal(r.win,0);A.reward(p,r.game,'train');assert(p.roster.includes('slardar'));assert.equal(p.growth.health,1);assert.equal(p.upgrades.essence,1);assert.throws(()=>A.reward(p,r.game,'train'));ArtifactCampaignDeck.claim(p,'skip');const h=new A.CampaignGame(cards);h.begin(p);assert.equal(h.all(0)[0].damage,0);assert.equal(h.stats(h.all(0)[0]).health,23);});
test('scepter stays spent in serialized journey and cannot be recast',()=>{const p=profile(10);p.scepter=true;const g=new A.CampaignGame(cards);g.begin(p);g.cast('story_scepter');assert(g.s.scepterUsed);assert.throws(()=>g.cast('story_scepter'));p.scepterUsed=true;p.battle=g.s;assert(A.valid(JSON.parse(JSON.stringify(p))));p.battle=null;const h=new A.CampaignGame(cards);h.begin(p);assert.throws(()=>h.cast('story_scepter'));});
test('betrayed companions return as enemies; resonance is stripped and backlashes',()=>{const p=profile(17);p.resonance=30;A.abandon(p,'magnus');const g=new A.CampaignGame(cards);g.begin(p);assert(g.all(1).some(u=>u.k==='magnus'));assert(!g.all(0).some(u=>u.k==='magnus'));const u=g.all(0).find(u=>u.k==='slark');assert.equal(u.damage,Math.floor(p.resonance/3));assert.equal(g.stats(u).attack,5+Math.floor(p.growth.attack*.35));});
test('reload is deterministic and serialized campaign never includes a Classic save',()=>{const g=game(2),h=new A.CampaignGame(cards);h.s=JSON.parse(JSON.stringify(g.s));g.combat();h.combat();assert.deepEqual(g.s,h.s);assert(!JSON.stringify(g.s).includes('artifact.match'));});
test('all eighteen stages have dialogue, objectives, and local portraits',()=>{assert.equal(D.stages.length,18);for(const s of D.stages){assert(s.intro.length>=2);assert(s.outro&&s.clue&&D.objectives[s.kind]);}for(const c of D.heroes)assert(fs.existsSync('dist/'+c.art));});
/* --- multi-scene stages --- */
test('multi-scene stages save progress per scene and defeat retries only that scene',()=>{const p=A.fresh();const g1=new A.CampaignGame(cards);g1.begin(p,7);assert.equal(g1.scene().enemy,'gaoler');assert.equal(g1.s.scene,0);assert.equal(simulate(g1).win,0);A.advanceScene(p,g1);assert.equal(p.scene,1);assert.equal(p.battle,null);assert(A.valid(JSON.parse(JSON.stringify(p))));const g2=new A.CampaignGame(cards);g2.begin(p,7);assert.equal(g2.scene().enemy,'slardar');assert.equal(g2.s.scene,1);assert.throws(()=>A.reward(p,g2,'bond'));g2.s.winner=1;assert.throws(()=>A.advanceScene(p,g2));assert.equal(p.scene,1,'defeat retries the same scene');});
test('advanceScene requires a win and refuses past the final scene',()=>{const p=A.fresh(),g=new A.CampaignGame(cards);g.begin(p,7);assert.throws(()=>A.advanceScene(p,g));p.scene=1;const g2=new A.CampaignGame(cards);g2.begin(p,7);g2.s.winner=0;assert.throws(()=>A.advanceScene(p,g2));});
test('choice events write to save and journal and are one-time only',()=>{const p=profile(4);p.stage=5;p.completed.push(4);const gold=p.gold;A.applyChoice(p,'crossroads','pursue');assert.equal(p.choices.crossroads,'pursue');assert(p.gold>gold);assert.equal(p.nextMods.forStage,5);assert(p.journal.at(-1).choice==='event');assert.throws(()=>A.applyChoice(p,'crossroads','escort'));const mods=p.nextMods;const g=new A.CampaignGame(cards);g.begin(p,3);const boss=g.all(1).find(u=>u.k===g.scene().enemy);assert.equal(g.stats(boss).health,g.scene().hp+mods.enemyHp+(p.stigma[g.scene().stigma]||0));});
test('single-scene stages still work without a scenes array',()=>{const p=profile(3),g=new A.CampaignGame(cards);g.begin(p,3);assert.equal(A.sceneCount(D.stages[3]),1);assert.equal(g.s.scene,0);g.s.winner=0;A.reward(p,g,'bond');assert.equal(p.stage,4);assert.equal(p.scene,0);});
test('scene stats, lanes and rules come from the scene, not the stage shell',()=>{const g=game(4,0);assert.equal(g.scene().kind,'clear');assert.equal(g.scene().enemy,'veil_blade');const g2=game(4,1);assert.equal(g2.scene().kind,'defend');assert.equal(g2.scene().enemy,'phantom_assassin');assert.equal(g2.s.lanes[0].towers[0].hp,g2.scene().coreHp||34);});
test('bounty marks bank supplies at scene and stage boundaries',()=>{const p=profile(0),g=new A.CampaignGame(cards);g.begin(p,1);const e=g.all(1)[0];hand(g,'story_mark');g.cast('story_mark',e.uid);assert(g.flag(e,'bountyMark'));const before=p.gold;for(const u of g.all(1))g.damage(u,999,true);g.sweep();assert(g.s.contracts>=12);g.s.winner=0;A.advanceScene(p,g);assert.equal(p.gold,before+g.s.contracts);});
/* --- sentry kind --- */
test('sentry scene spawns a guard each round and a live guard at round end is defeat',()=>{const g=game(10,0);assert.equal(g.scene().kind,'sentry');const s1=g.all(1).find(u=>g.flag(u,'sentry'));assert(s1,'sentry spawned at begin');assert.equal(g.s.players[0].hand.filter(h=>h.k==='story_silence').length,2);g.combat();assert.equal(g.s.winner,1,'surviving sentry sounds the alarm');});
test('killing the sentry each round keeps the infiltration alive; warden death wins',()=>{const g=game(10,0);const s1=g.all(1).find(u=>g.flag(u,'sentry'));const h=g.s.players[0].hand.find(h=>h.k==='story_silence');g.cast('story_silence',s1.uid);assert(!s1.alive);g.combat();assert.equal(g.s.winner,null);assert.equal(g.s.round,2);const g2=game(10,0);for(const u of g2.all(1).filter(u=>!g2.flag(u,'sentry')))g2.damage(u,999,true);g2.sweep();assert.equal(g2.s.winner,0,'non-sentry clear wins even with a live sentry');});
test('attack actions still raise the alarm during sentry infiltration',()=>{const g=game(10,0),e=g.all(1).find(u=>!g.flag(u,'sentry'));hand(g,'story_pounce');g.cast('story_pounce',e.uid);assert.equal(g.s.alarm,1);const f=g.combatForecast();assert.equal(f.units[e.uid].damage,0);});
/* --- elites --- */
test('veil enemies deal bonus critical damage in forecast and combat',()=>{const g=game(4,0);const f=g.combatForecast();const a=f.attacks.find(a=>g.flag(g.get(a.unit),'veil'));assert(a,'a veiled enemy attacks');const e=g.get(a.unit),t=g.get(a.target),sa=g.stats(e);assert.equal(f.units[t.uid].damage,Math.max(0,sa.attack+Math.ceil(sa.attack/2)-g.stats(t).armor));});
test('dragon trial regenerates the champion and shields the egg-bearer',()=>{const g=game(11);const boss=g.all(1).find(u=>u.k==='winter_wyvern');assert(g.value(boss,'regen')>=4);const slark=g.all(0).find(u=>u.k==='slark');assert(g.stats(slark).armor>=2);});
test('rampage adds attack every round',()=>{const g=game(3);const boss=g.all(1).find(u=>u.hero);const a=g.stats(boss).attack;g.combat();assert.equal(g.stats(g.get(boss.uid)).attack,a+1);});
/* --- choice events --- */
test('events only fire at their appointed stage',()=>{const p=profile(4);p.stage=4;assert.throws(()=>A.applyChoice(p,'crossroads','pursue'));});
/* --- migration --- */
test('pre-change v1 save migrates safely and validates',()=>{const old=A.fresh();delete old.scene;delete old.choices;delete old.tuning;delete old.drill;delete old.nextMods;old.stage=2;old.roster=['slark','slardar','enchantress'];old.party=[...old.roster];for(const k of old.party)old.loyalty[k]=3;ArtifactCampaignDeck.migrate(old);assert(A.valid(old));assert.equal(old.scene,0);assert.deepEqual(old.choices,{});});
test('old mid-battle save on a now-multi-scene stage lands on its final scene',()=>{const old=A.fresh();old.stage=4;old.roster=['slark','slardar','enchantress','bounty_hunter','phantom_assassin'];old.party=[...old.roster];for(const k of old.party)old.loyalty[k]=3;const g=new A.CampaignGame(cards);g.begin(old,5);old.battle=JSON.parse(JSON.stringify(g.s));delete old.battle.scene;delete old.scene;delete old.choices;delete old.tuning;delete old.drill;delete old.nextMods;ArtifactCampaignDeck.migrate(old);assert.equal(old.scene,1);assert.equal(old.battle.scene,1);assert(A.valid(old),'migrated mid-battle save validates');});
/* --- new cards --- */
test('phantom strike refunds on kill and stays quiet in infiltration',()=>{const g=game(0,1),e=g.all(1)[0];e.damage=g.stats(e).health-4;hand(g,'story_phantom');const handBefore=g.s.players[0].hand.length;g.cast('story_phantom',e.uid);assert(!e.alive);assert.equal(g.s.players[0].hand.length,handBefore,'kill draws a card back');const g2=game(10,1),e2=g2.all(1)[0];hand(g2,'story_phantom');g2.cast('story_phantom',e2.uid);assert.equal(g2.s.alarm,0);});
test('wyrmkin oath summons a dragon ally that blocks',()=>{const g=game();hand(g,'story_wyrm');const n=g.all(0).length;g.cast('story_wyrm');assert.equal(g.all(0).length,n+1);const w=g.all(0).find(u=>u.k==='whelp');assert(w&&w.alive);});
test('seal-stone vigil raises a ward; scales grant armor and regen',()=>{const g=game(),u=g.all(0)[0];hand(g,'story_ward');g.cast('story_ward');assert(g.all(0).some(u=>u.k==='stone_ward'));hand(g,'story_scales');g.cast('story_scales',u.uid);assert(g.stats(u).armor>=2);assert(g.value(u,'regen')>=2);});
test('moon-mute seal shatters armor and binds',()=>{const g=game(),e=g.all(1)[0];hand(g,'story_seal');const ar=g.stats(e).armor;g.cast('story_seal',e.uid);assert.equal(g.stats(e).armor,ar-4);assert(g.flag(e,'stun'));assert(g.flag(e,'root'));});
test('essence shift refunds two mana after the forge',()=>{const p=profile(6);p.forge=true;p.upgrades.essence=0;const g=new A.CampaignGame(cards);g.begin(p,3);const e=g.all(1)[0];hand(g,'story_essence');const mana=g.s.lanes[0].mana[0];g.cast('story_essence',e.uid);assert.equal(g.s.lanes[0].mana[0],mana-2+2,'mana cost 2 then +2 refund');});
test('temper boon raises drill and tunes a deck card',()=>{const p2=profile(3);const g2=new A.CampaignGame(cards);g2.begin(p2,1);g2.s.winner=0;A.reward(p2,g2,'temper');assert.equal(p2.drill,1);assert(Object.values(p2.tuning).reduce((a,b)=>a+b,0)>=1);});
test('stage 11 grants the dragon oath card',()=>{const p=profile(11);const g=new A.CampaignGame(cards);g.begin(p,1);g.s.winner=0;A.reward(p,g,'bond');assert(p.deck.includes('story_wyrm'));});
test('enemy-only cards never appear in offers',()=>{const p=profile(5);for(let s=0;s<18;s++){const o=ArtifactCampaignDeck.offers(p,s);for(const k of o)assert(!k.startsWith('story_foe'));}});
console.log(count+' campaign suites passed');
