const assert=require('node:assert/strict'),fs=require('node:fs');const cards=require('../dist/cards.json');const {Game,clone}=require('../dist/engine.js');require('../dist/effects.js');require('../dist/decks.js');const proto={combat:Game.prototype.combat,checkWin:Game.prototype.checkWin,stats:Game.prototype.stats};const D=require('../dist/campaign-data.js'),A=(require('../dist/campaign-deck.js'),require('../dist/campaign-engine.js'));const {simulate}=require('./campaign-simulation.cjs');let count=0;
function test(name,fn){try{fn();console.log('PASS',name);count++;}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
function profile(stage=0){const p=A.fresh();p.stage=stage;if(stage){p.roster=['slark','slardar','magnus','enchantress','bounty_hunter'];p.party=[...p.roster];for(const k of p.roster)p.loyalty[k]=3;p.growth={attack:stage*.5,health:stage};}return p;}
function game(stage=0){const g=new A.CampaignGame(cards);g.begin(profile(stage),123);return g;}
function hand(g,k){g.s.players[0].hand.push({uid:g.id(),k,lock:0});g.s.lanes[g.s.lane].mana[0]=20;}
test('Classic catalog and prototype methods are untouched',()=>{assert.equal(cards.filter(c=>!c.expansion).length,303);for(const k in proto)assert.equal(Game.prototype[k],proto[k]);const g=new Game(cards);g.newGame(ARTIFACT_DECKS[0],ARTIFACT_DECKS[1],77);assert.equal(g.s.lanes.length,3);assert.equal(g.card('slark'),undefined);g.towerDamage(1,0,40);g.checkWin();assert.equal(g.s.lanes[0].towers[1].hp,80);assert.equal(g.s.winner,null);});
test('mandatory Slark, unique roster and at most five heroes',()=>{const p=profile(5);assert(A.valid(p));assert.throws(()=>A.chooseParty(p,'slark'));p.roster.push('tiny');p.loyalty.tiny=2;assert.throws(()=>A.chooseParty(p,'tiny'));A.chooseParty(p,'magnus');A.chooseParty(p,'tiny');assert.equal(p.party.length,5);p.party[0]='tiny';assert(!A.valid(p));});
test('save validation rejects broken or incompatible payloads',()=>{for(const change of [p=>p.version=9,p=>p.gold=NaN,p=>p.deck=['invalid'],p=>p.weapon='invalid',p=>p.battle={chapter:0}]){const p=A.fresh();change(p);assert(!A.valid(p));}});
test('one/two/three fronts contain no units or actions in inactive lanes',()=>{for(const n of [0,2,14]){const g=game(n),lanes=D.stages[n].lanes;assert.equal(g.s.activeLanes,lanes);assert(g.all().every(u=>u.lane<lanes));for(let l=0;l<lanes;l++)g.combat();if(g.s.winner===null){assert.equal(g.s.round,2);assert.equal(g.s.lane,0);assert.equal(g.s.phase,'action');}assert(!g.s.log.some(e=>e.type==='lane'&&e.lane>=lanes));}});
test('initial hero assignments and once-per-round movement preserve unique positions',()=>{const p=profile(2);p.placements=Object.fromEntries(p.party.map(k=>[k,1]));const g=new A.CampaignGame(cards);g.begin(p);assert.equal(g.all(0,1).filter(u=>u.hero).length,5);assert.equal(new Set(g.all(0,1).map(u=>u.pos)).size,5);g.relocate(g.all(0,1)[0].uid,0);assert.throws(()=>g.relocate(g.all(0,1)[0].uid,0));});
test('party wipe loses even with surviving summoned units and no tower damage',()=>{const g=game();g.spawnAlly(0);for(const u of g.all(0).filter(u=>u.hero))g.damage(u,999,true);g.sweep();assert.equal(g.s.winner,1);assert(g.all(0).some(u=>!u.hero));});
test('simultaneous last hero and last enemy death is defeat, not victory',()=>{const g=game();for(const u of g.all())g.damage(u,999,true);g.sweep();assert.equal(g.s.winner,1);});
test('elimination ignores tower damage, assault requires every seal',()=>{const g=game();g.towerDamage(0,0,999);g.checkWin();assert.equal(g.s.winner,null);const a=game(14);for(let l=0;l<2;l++)a.towerDamage(1,l,999);a.checkWin();assert.equal(a.s.winner,null);a.towerDamage(1,2,999);a.checkWin();assert.equal(a.s.winner,0);});
test('defense victory checks waves and loss checks every friendly core',()=>{const g=game(2);g.s.round=4;g.s.lane=1;g.combat();assert.equal(g.s.winner,0);const p=profile(2);p.battle=g.s;assert(A.valid(p),'ended defense save must reload');const h=game(2);h.towerDamage(0,1,999);h.checkWin();assert.equal(h.s.winner,1);});
test('invalid target cannot spend mana or remove a card; equipment is hero only',()=>{const g=game();hand(g,'story_blade');const before=clone(g.s);assert.throws(()=>g.cast('story_blade',g.all(1)[0].uid));assert.deepEqual(g.s,before);const u=g.spawnAlly(0);assert.throws(()=>g.cast('story_blade',u.uid));const hero=g.all(0).find(u=>u.hero);g.cast('story_blade',hero.uid);assert.equal(hero.items.Weapon.k,'short_sword');});
test('healing, armor and direct damage use existing shared rules',()=>{const g=game(),u=g.all(0)[0],e=g.all(1)[0];g.damage(u,9,true);hand(g,'story_salve');g.cast('story_salve',u.uid);assert.equal(u.damage,3);hand(g,'story_essence');g.cast('story_essence',e.uid);assert.equal(e.damage,5);assert.equal(g.stats(u).attack,6);});
test('stealth has no automatic outgoing damage and two loud casts lose',()=>{const g=game(10),e=g.all(1)[0],forecast=g.combatForecast();assert.equal(forecast.units[e.uid].damage,0);hand(g,'story_pounce');g.cast('story_pounce',e.uid);assert.equal(g.s.alarm,1);hand(g,'story_essence');g.cast('story_essence',e.uid);assert.equal(g.s.winner,1);});
test('time puzzle cannot win before casting rewind',()=>{const g=game(13);for(const e of g.all(1))g.damage(e,999,true);g.sweep();assert.equal(g.s.winner,null);hand(g,'story_rewind');g.cast('story_rewind',g.all(0)[0].uid);assert.equal(g.s.winner,0);});
test('discard recycling never deals dead heroes or creeps as cards',()=>{const g=game();g.s.players[0].hand=[];g.s.players[0].deck=[];g.s.players[0].discard=['melee_creep','slark','story_guard'];g.drawCards(3);assert.deepEqual(g.s.players[0].hand.map(h=>h.k),['story_guard']);});
test('rewards are once only, recruit enemies, persist growth and restore at camp',()=>{const p=A.fresh(),g=new A.CampaignGame(cards);g.begin(p,123);assert.equal(simulate(g).win,0);A.reward(p,g,'train');assert(p.roster.includes('slardar'));assert.equal(p.growth.health,1);assert.equal(p.upgrades.essence,1);assert.throws(()=>A.reward(p,g,'train'));ArtifactCampaignDeck.claim(p,'skip');const h=new A.CampaignGame(cards);h.begin(p);assert.equal(h.all(0)[0].damage,0);assert.equal(h.stats(h.all(0)[0]).health,23);});
test('scepter stays spent in serialized journey and cannot be recast',()=>{const p=profile(10);p.scepter=true;const g=new A.CampaignGame(cards);g.begin(p);g.cast('story_scepter');assert(g.s.scepterUsed);assert.throws(()=>g.cast('story_scepter'));p.scepterUsed=true;p.battle=g.s;assert(A.valid(JSON.parse(JSON.stringify(p))));p.battle=null;const h=new A.CampaignGame(cards);h.begin(p);assert.throws(()=>h.cast('story_scepter'));});
test('betrayed companions return as enemies; resonance is stripped and backlashes',()=>{const p=profile(17);p.resonance=30;A.abandon(p,'magnus');const g=new A.CampaignGame(cards);g.begin(p);assert(g.all(1).some(u=>u.k==='magnus'));assert(!g.all(0).some(u=>u.k==='magnus'));const u=g.all(0).find(u=>u.k==='slark');assert.equal(u.damage,Math.floor(p.resonance/3));assert.equal(g.stats(u).attack,5+Math.floor(p.growth.attack*.35));});
test('reload is deterministic and serialized campaign never includes a Classic save',()=>{const g=game(2),h=new A.CampaignGame(cards);h.s=JSON.parse(JSON.stringify(g.s));g.combat();h.combat();assert.deepEqual(g.s,h.s);assert(!JSON.stringify(g.s).includes('artifact.match'));});
test('all eighteen stages have dialogue, objectives, and local portraits',()=>{assert.equal(D.stages.length,18);for(const s of D.stages){assert(s.intro.length>=2);assert(s.outro&&s.clue&&D.objectives[s.kind]);}for(const c of D.heroes)assert(fs.existsSync('dist/'+c.art));});
console.log(count+' campaign suites passed');
