const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cards=require('../dist/cards.json');require('../dist/engine.js');require('../dist/effects.js');const D=require('../dist/campaign-data.js'),K=require('../dist/campaign-deck.js'),A=require('../dist/campaign-engine.js');let n=0;function test(name,fn){try{fn();console.log('PASS',name);n++;}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
function profile(stage=0,scene=0){const p=A.fresh();p.stage=stage;p.scene=scene;p.gold=150;if(stage){p.roster=['slark','slardar','magnus','enchantress','bounty_hunter'];p.party=[...p.roster];for(const k of p.party)p.loyalty[k]=3;}return p;}
function g(stage=0,scene=0){const game=new A.CampaignGame(cards);game.begin(profile(stage,scene));return game;}
function give(game,k){const h={uid:game.id(),k,lock:0};game.s.players[0].hand.push(h);game.s.lanes[game.s.lane].mana[0]=20;return h;}
test('reward offers persist through JSON reload and cannot be rerolled or double claimed',()=>{const p=profile(3),game=g(3);game.s.winner=0;A.reward(p,game,'bond');const original=[...p.cardReward.offers],q=JSON.parse(JSON.stringify(p));assert.deepEqual(q.cardReward.offers,original);assert.equal(new Set(original).size,3);const before=q.deck.length;K.claim(q,original[1]);assert.equal(q.deck.length,before+1);assert.throws(()=>K.claim(q,original[0]));assert.equal(q.journal.at(-1).card,original[1]);});
test('pending reward blocks next encounter, invalid picks do not mutate, skip keeps deck',()=>{const p=profile(3),game=g(3);game.s.winner=0;A.reward(p,game,'train');assert.throws(()=>game.begin(p));const before=JSON.stringify(p);assert.throws(()=>K.claim(p,'story_invalid'));assert.equal(JSON.stringify(p),before);const size=p.deck.length;K.claim(p,'skip');assert.equal(p.deck.length,size);game.begin(p);});
test('camp upgrades exactly one physical copy and charges once',()=>{const p=profile(),copies=p.deck.filter(k=>k==='story_pounce').length;K.upgrade(p,'story_pounce');assert.equal(p.deck.filter(k=>k==='story_pounce').length,copies-1);assert.equal(p.deck.filter(k=>k==='story_pounce_plus').length,1);assert.equal(p.gold,100);assert.throws(()=>K.upgrade(p,'story_pounce'));});
test('removal is paid, limited per camp, and cannot delete below eight cards',()=>{const p=profile();K.remove(p,'story_guard');assert.equal(p.gold,115);assert.equal(p.deck.length,11);assert.throws(()=>K.remove(p,'story_guard'));p.campActions={};p.deck=p.deck.slice(0,8);assert.throws(()=>K.remove(p,p.deck[0]));});
test('new rounds discard unspent hand and draw five, and recycled deck contains no dead units',()=>{const game=g(2),ids=new Set(game.s.players[0].hand.map(h=>h.uid));game.s.players[0].discard.push('melee_creep');game.nextRound();assert.equal(game.s.players[0].hand.length,5);assert(game.s.players[0].hand.every(h=>!ids.has(h.uid)));assert(game.s.players[0].hand.every(h=>D.cards.some(c=>c.key===h.k)));});
test('upgraded card costs and damage really change, including original renderer play API',()=>{const game=g(),e=game.all(1)[0],h=give(game,'story_pounce_plus');game.play(0,h.uid,[e.uid]);assert.equal(e.damage,8);assert(game.flag(e,'disarm'));const cast=game.s.events.find(e=>e.type==='card');assert.equal(cast.card,h.k);assert(cast.targets[0].uid===e.uid);assert(cast.outcomes.some(o=>o.changes.some(t=>t.includes('伤害'))));assert.equal(game.card('story_blink_plus').mana,0);});
test('blink has a source and destination, moves only to an active lane, and records movement',()=>{const game=g(2),u=game.all(0,0)[0],h=give(game,'story_blink');assert.deepEqual(game.targets(h.k).map(s=>s.kind),['unit','lane']);const before=JSON.stringify(game.s);assert.throws(()=>game.play(0,h.uid,[u.uid,2]));assert.equal(JSON.stringify(game.s),before);game.play(0,h.uid,[u.uid,1]);assert.equal(u.lane,1);assert(game.s.events.find(e=>e.type==='card').outcomes.some(o=>o.changes.some(t=>t.includes('转移'))));});
test('poison enables conditional ambush damage and ticks through the existing beforeAction',()=>{const game=g(),e=game.all(1)[0];give(game,'story_venom');game.cast('story_venom',e.uid);assert.equal(e.damage,2);game.beforeAction(0);assert.equal(e.damage,4);give(game,'story_ambush');game.cast('story_ambush',e.uid);assert.equal(e.damage,11);});
test('three-lane pursuers telegraph and execute equipment blink, while control cancels it',()=>{const game=g(4,1);assert.equal(game.s.activeLanes,3);let i=game.s.pursuitIntent,u=game.get(i.unit);assert.equal(u.items.Weapon.k,'blink_dagger');assert.notEqual(i.from,i.lane);const dest=i.lane;game.nextRound();assert.equal(u.lane,dest);assert(game.s.events.some(e=>e.type==='ability'&&e.card==='blink_dagger'));const blocked=g(4,1),intent=blocked.s.pursuitIntent,hunter=blocked.get(intent.unit),from=hunter.lane;blocked.buff(hunter,{disarm:1},'round');blocked.nextRound();assert.equal(hunter.lane,from);assert(blocked.s.log.some(e=>e.text.includes('闪烁取消')));});
test('classic geometry default stays identical and variable-front overview centers correctly',()=>{const B=require('../dist/board.js');assert.deepEqual(B.layout(1280,800,null),B.layout(1280,800,null,false,0,3));for(const fronts of [1,2,3]){const r=B.layout(1280,800,null,false,0,fronts);assert(Math.abs(r.width-(r.laneWidth*fronts+4*(fronts-1)))<.001);assert.equal(r.x,(1280-r.width)/2);}});
test('native campaign entry loads original renderer and effect modules, not the removed mini-board',()=>{const html=fs.readFileSync('dist/campaign-battle.html','utf8');for(const f of ['app.js','scene.js','board.js','board-input.js','battle-scene.css','board-layout.css'])assert(html.includes(f));assert(!html.includes('campaign-app.js'));assert(!fs.readFileSync('dist/campaign-app.js','utf8').includes('function lane(l)'));});
test('bridge writes campaign save and never overwrites the Classic match',()=>{const p=profile(),game=g();p.scepter=true;game.s.profile.scepter=true;p.battle=game.s;const memory={[A.SAVE_KEY]:JSON.stringify(p),'artifact.match':'CLASSIC_SENTINEL'},ctx={ArtifactCampaign:A,ArtifactCampaignData:D,ArtifactCampaignDeck:K,ArtifactI18n:require('../dist/i18n.js'),ARTIFACT_CARDS:cards,localStorage:{getItem:k=>memory[k],setItem:(k,v)=>memory[k]=v},document:{body:{classList:{toggle(){},add(){}}}},location:{replace(){throw Error('Unexpected redirect');}}};ctx.window=ctx;vm.runInNewContext(fs.readFileSync('dist/campaign-bridge.js','utf8'),ctx);ctx.ArtifactCampaignBridge.save(ctx.ArtifactCampaignBridge.game.s);assert.equal(memory['artifact.match'],'CLASSIC_SENTINEL');assert(A.valid(JSON.parse(memory[A.SAVE_KEY])));const advanced=JSON.parse(memory[A.SAVE_KEY]);advanced.stage=1;advanced.battle=null;memory[A.SAVE_KEY]=JSON.stringify(advanced);ctx.ArtifactCampaignBridge.save(ctx.ArtifactCampaignBridge.game.s);assert.equal(JSON.parse(memory[A.SAVE_KEY]).stage,1,'stale battle must not overwrite later chapter');});
console.log(n+' campaign deck/native suites passed');
