'use strict';
const assert=require('node:assert/strict'),{test}=require('node:test');
const cards=require('../dist/cards.json'),{Game,clone}=require('../dist/engine');
require('../dist/effects');require('../dist/decks');
const {project}=require('../dist/online-bridge');
const EXPANSION_DECK=ARTIFACT_DECKS.find(d=>d.id==='dark-willow-pangolier'),MK_DECK=ARTIFACT_DECKS.find(d=>d.id==='monkey-king');
function arena(seed=83){const g=new Game(cards);g.newGame(EXPANSION_DECK,ARTIFACT_DECKS[0],seed);g.s.units=[];g.s.events=[];g.s.jex=[];g.s.lane=0;g.s.turn=0;g.s.phase='action';for(const p of g.s.players)p.hand=[];g.s.lanes[0].mana=[100,100];return g;}
function spawn(g,k,p,pos){const u=g.spawn(k,p,0,pos);u.cooldowns={};return u;}
function cast(g,k,t=[],p=0){g.s.turn=p;const h={uid:g.id(),k,lock:0};g.s.players[p].hand.push(h);g.play(p,h.uid,t);return g.s;}
function nextRound(g){g.s.phase='shop';g.startRound();}

test('expansion decks are valid; signatures auto-include and rebuild data stays in sync',()=>{const g=arena();for(const d of [EXPANSION_DECK,MK_DECK])assert.deepEqual(g.validateDeck(d),[]);const h=new Game(cards);h.newGame(EXPANSION_DECK,ARTIFACT_DECKS[0],12);for(const k of ['pangolier_lucky_shot','dark_willow_bramble_maze'])assert.equal([...h.s.players[0].deck,...h.s.players[0].hand].filter(c=>c.k===k).length,3);const m=new Game(cards);m.newGame(MK_DECK,ARTIFACT_DECKS[0],12);assert.equal([...m.s.players[0].deck,...m.s.players[0].hand].filter(c=>c.k==='monkey_king_command').length,3);assert.equal(cards.filter(c=>c.expansion==='dota2').length,14);});

test('Shield Crash grants shield only for real damage and absorbs across hits until round end',()=>{const g=arena(),u=spawn(g,'pangolier',0,1),hero=spawn(g,'dark_willow',1,0),creep=spawn(g,'melee_creep',1,1),armored=spawn(g,'axe',1,2);g.buff(armored,{armor:9});g.activate(0,u.uid,u.k);assert.equal(hero.damage,2);assert.equal(creep.damage,2);assert.equal(armored.damage,0);assert.equal(g.shield(u),3);assert.equal(g.damage(u,2,true),0);assert.equal(g.shield(u),1);assert.equal(g.damage(u,3,true),2);assert.equal(g.shield(u),0);g.buff(u,{shield:4},'round');nextRound(g);assert.equal(g.shield(u),0);});

test('forecast consumes a shared shield budget and agrees with simultaneous combat',()=>{const g=arena(),u=spawn(g,'pangolier',0,1);spawn(g,'melee_creep',1,0).target=u.uid;spawn(g,'melee_creep',1,1).target=u.uid;g.buff(u,{shield:3},'round');const f=g.combatForecast();assert.equal(f.units[u.uid].shieldSpent,3);assert.equal(f.units[u.uid].damage,1);g.combat();assert.equal(u.damage,1);assert.equal(g.shield(u),0);});

test('an absorbed attack does not proc Fury Swipes because another attacker penetrated the shield',()=>{const g=arena(),u=spawn(g,'pangolier',0,0),ursa=spawn(g,'ursa',1,0);spawn(g,'melee_creep',1,1).target=u.uid;g.buff(u,{shield:g.stats(ursa).attack},'round');g.combat();assert.equal(u.damage,2);assert.equal(g.value(u,'armor'),0);});

test('Lucky Shot has seeded success and failure branches and one-round disarm',()=>{const results=new Set();for(let seed=1;seed<36;seed++){const g=arena(seed);spawn(g,'pangolier',0,0);const u=spawn(g,'dark_willow',1,0);cast(g,'pangolier_lucky_shot',[u.uid]);assert.equal(u.damage,2);results.add(g.flag(u,'disarm'));nextRound(g);assert(!g.flag(u,'disarm'));}assert.deepEqual(results,new Set([true,false]));});

test('flowers fill only existing friendly gaps, retaliate on attacks and expire without bounty',()=>{const g=arena();spawn(g,'dark_willow',0,0);const enemy=spawn(g,'pangolier',1,1);spawn(g,'axe',1,2);cast(g,'dark_willow_bramble_maze');const flowers=g.all(0,0).filter(u=>u.k==='dark_willow_bramble');assert.deepEqual(flowers.map(u=>u.pos),[1,2]);for(const u of flowers){assert.equal(g.stats(u).attack,0);assert.equal(g.stats(u).hp,1);}g.battle(enemy,flowers[0]);assert.equal(enemy.damage,1);assert(g.flag(enemy,'root'));const gold=g.s.players.map(p=>p.gold);nextRound(g);assert.equal(g.all().filter(u=>u.k==='dark_willow_bramble').length,0);assert.deepEqual(g.s.players.map(p=>p.gold),gold);assert(!g.flag(enemy,'root'));});

test('flower recoil/root works in combat forecast and actual simultaneous combat',()=>{const g=arena(),a=spawn(g,'pangolier',0,0),b=spawn(g,'dark_willow_bramble',1,0);g.buff(b,{immune:1},'round');const f=g.combatForecast();assert.equal(f.units[a.uid].damage,1);assert(f.roots.includes(a.uid));g.combat();assert.equal(a.damage,1);assert(g.flag(a,'root'));});

test('root blocks movement, swaps, blink and return with complete action rollback',()=>{const g=arena(),u=spawn(g,'pangolier',0,0),ally=spawn(g,'axe',0,1);u.items.Weapon={k:'blink_dagger'};g.buff(u,{root:1},'round');assert.throws(()=>g.move(u,1),/缠绕/);assert.throws(()=>g.swap(u,ally),/缠绕/);assert.throws(()=>g.returnHero(u),/缠绕/);assert.match(g.canActivate(0,u.uid,'blink_dagger'),/缠绕/);let before=clone(g.s);assert.throws(()=>g.activate(0,u.uid,'blink_dagger',[1]),/缠绕/);assert.deepEqual(g.s,before);const h={uid:g.id(),k:'town_portal_scroll',lock:0};g.s.players[0].hand.push(h);before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[u.uid]),/缠绕/);assert.deepEqual(g.s,before);});

test('Shadow Realm blocks attacks but permits spell damage, matching-color stacks cap at 3 and one attack consumes it',()=>{const g=arena(),u=spawn(g,'dark_willow',0,0);spawn(g,'pangolier',0,1);const enemy=spawn(g,'axe',1,0);spawn(g,'dark_willow',1,1);g.activate(0,u.uid,u.k);assert.equal(g.value(u,'shadowBonus'),1);cast(g,'defensive_stance',[u.uid]);assert.equal(g.value(u,'shadowBonus'),1,'red card must not stack on a black hero');cast(g,'short_sword',[u.uid]);assert.equal(g.value(u,'shadowBonus'),1,'colorless item must not stack');u.items={};cast(g,'dark_willow_bramble_maze',[],1);assert.equal(g.value(u,'shadowBonus'),1,'opponent cards must not stack');for(let i=0;i<4;i++){cast(g,'dark_willow_bramble_maze');assert.equal(g.value(u,'shadowBonus'),Math.min(3,2+i));}assert(!g.combatForecast().attacks.some(a=>a.unit===enemy.uid));assert.equal(g.damage(u,1,true),1);g.battle(enemy,u);assert.equal(u.damage,1);assert.equal(enemy.damage,4);assert(!g.flag(u,'shadowRealm'));assert.equal(g.stats(u).attack,3);});

test('Shadow Realm follows hero color metadata rather than a hardcoded color',()=>{const alternate=clone(cards);alternate.find(c=>c.key==='dark_willow').color='Red';const g=new Game(alternate);g.s=arena().s;const u=spawn(g,'dark_willow',0,0);spawn(g,'bounty_hunter',0,1);spawn(g,'axe',1,0);g.activate(0,u.uid,u.k);cast(g,'dark_willow_bramble_maze');assert.equal(g.value(u,'shadowBonus'),1);cast(g,'defensive_stance',[u.uid]);assert.equal(g.value(u,'shadowBonus'),2);});

test('Shadow Realm bonus applies once to tower attack and survives a disarmed combat',()=>{const g=arena(),u=spawn(g,'dark_willow',0,0);g.activate(0,u.uid,u.k);g.buff(u,{disarm:1},'round');g.combat();assert(g.flag(u,'shadowRealm'));g.s.lane=0;g.s.phase='action';u.mods=u.mods.filter(m=>!m.disarm);const hp=g.s.lanes[0].towers[1].hp;assert.equal(g.combatForecast().tower[1],4);g.combat();assert.equal(g.s.lanes[0].towers[1].hp,hp-4);assert(!g.flag(u,'shadowRealm'));});

test('normal Jex waits for next own spell, not its summoning card, equipment, enemy spell or hero ability',()=>{const g=arena(),u=spawn(g,'dark_willow',0,0),e=spawn(g,'pangolier',1,0);cast(g,'dark_willow_terrorize',[{lane:0,pos:0}]);assert.equal(g.s.jex.length,1);g.s.turn=0;g.activate(0,u.uid,u.k);assert.equal(g.s.jex.length,1);cast(g,'short_sword',[u.uid]);assert.equal(g.s.jex.length,1);cast(g,'new_orders',[e.uid,u.uid],1);assert.equal(g.s.jex.length,1);cast(g,'grazing_shot',[e.uid]);assert.equal(g.s.jex.length,0);assert(g.flag(e,'disarm'));assert(!g.flag(e,'flipped'));assert.equal(e.damage,4);});

test('enhanced Jex snapshots flower, hits future opposite occupant for 3 then flips; marker persists through save/projection',()=>{const g=arena();spawn(g,'dark_willow',0,0);spawn(g,'dark_willow_bramble',0,1);const target=spawn(g,'pangolier',1,1);cast(g,'dark_willow_terrorize',[{lane:0,pos:1}]);assert.equal(g.s.jex.length,1);assert(g.s.jex[0].enhanced);const copy=new Game(cards);copy.s=JSON.parse(JSON.stringify(g.s));assert.deepEqual(project(project(g.s,1),1),g.s);cast(copy,'grazing_shot',[target.uid]);const t=copy.get(target.uid);assert.equal(t.damage,5);assert(copy.flag(t,'flipped'));assert.equal(copy.s.jex.length,0);assert(!copy.selectable(t));});

test('flipped unit cannot be selected, use skills, attack, take damage, be killed by spells or move',()=>{const g=arena(),u=spawn(g,'pangolier',0,0);spawn(g,'dark_willow',1,0);g.buff(u,{flipped:1},'round');assert(!g.enabled(u));assert.equal(g.damage(u,10,true),0);g.condemn(u);g.sweep();assert(u.alive);assert(!g.candidateTargets('grazing_shot',1).flat().includes(u.uid));assert.throws(()=>g.validateTargets(g.card('grazing_shot'),1,[u.uid]),/翻牌/);assert.throws(()=>g.activate(0,u.uid,u.k),/无法使用/);assert.throws(()=>g.move(g.get(u.uid),1),/翻牌/);assert.equal(g.combatForecast().units[u.uid].damage,0);assert(!g.combatForecast().attacks.some(a=>a.unit===u.uid));});

test('opposing hero deals exactly half final tower damage including fractions; opposing creep cannot attack a flipped blocker',()=>{for(const attacker of ['dark_willow','melee_creep']){const g=arena(),u=spawn(g,attacker,0,0),e=spawn(g,'pangolier',1,0);g.buff(e,{flipped:1},'round');const expected=u.hero?1.5:0,f=g.combatForecast();assert.equal(f.tower[1],expected);g.combat();assert.equal(g.s.lanes[0].towers[1].hp,40-expected);assert.equal(e.damage,0);nextRound(g);assert(!g.flag(e,'flipped'));}});

test('rolling path is seeded, hits real curve contacts at most twice, moves by at most one empty slot and reserves destination',()=>{let doubleHit=false;for(let seed=1;seed<=25;seed++){const g=arena(seed),u=spawn(g,'pangolier',0,0);for(let pos=0;pos<6;pos++){const v=spawn(g,'dark_willow',1,pos);g.buff(v,{health:30});}spawn(g,'dark_willow',0,3);const saved=clone(g.s),other=new Game(cards);other.s=saved;cast(g,'pangolier_gyroshell',[{lane:0,pos:6}]);cast(other,'pangolier_gyroshell',[{lane:0,pos:6}]);assert.deepEqual(other.s,g.s);const event=g.s.events.find(e=>e.type==='rolling');assert(event.path.length>50);assert(event.hits.length>0);const counts={};for(const h of event.hits){counts[h.unit]=(counts[h.unit]||0)+1;assert(counts[h.unit]<=2);assert(Math.abs(h.toPos-h.fromPos)<=1);doubleHit ||= counts[h.unit]===2;}assert.equal(g.at(0,0,g.get(u.uid).pos)?.uid,u.uid);for(const v of g.all())assert.equal(g.all(v.owner,v.lane).filter(w=>w.pos===v.pos).length,1);}assert(doubleHit);});

test('ultimate validates source hero and same-lane slot before spending resources',()=>{const g=arena();spawn(g,'axe',0,0);let h={uid:g.id(),k:'pangolier_gyroshell',lock:0};g.s.players[0].hand.push(h);let before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[{lane:0,pos:1}]),/石鳞剑士/);assert.deepEqual(g.s,before);spawn(g,'pangolier',0,1);before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[{lane:1,pos:0}]));assert.deepEqual(g.s,before);assert.throws(()=>g.play(0,h.uid,[{lane:0,pos:999}]));assert.deepEqual(g.s,before);});

test('AI values delayed Jex setup and deck validation requires the ultimate hero',()=>{const g=arena(),u=spawn(g,'dark_willow',0,0);spawn(g,'pangolier',1,0);u.cooldowns.dark_willow=9;g.s.players[0].hand=[{uid:g.id(),k:'dark_willow_terrorize',lock:0}];assert.equal(g.bestAction(0)?.k,'dark_willow_terrorize');const deck=clone(EXPANSION_DECK);deck.heroes[0]='sven';assert(g.validateDeck(deck).some(e=>e.includes('石鳞剑士')));});

test('waiting Jex tracks shared column insertion and resolves after spell on-cast damage',()=>{const g=arena();spawn(g,'dark_willow',0,0);const flower=spawn(g,'dark_willow_bramble',0,1),enemy=spawn(g,'pangolier',1,1);cast(g,'dark_willow_terrorize',[{lane:0,pos:1}]);const zeus=spawn(g,'zeus',0,-1);g.move(zeus,0,3);assert.equal(g.s.jex[0].pos,flower.pos);assert.equal(enemy.pos,flower.pos);cast(g,'foresight');assert.equal(enemy.damage,4);assert(g.flag(enemy,'flipped'));});

test('new delayed effects survive authoritative room persistence and seat projection',()=>{const {Store}=require('../server/store.cjs'),{Match}=require('../server/match.cjs'),store=new Store(':memory:');try{const a=store.identity(),b=store.identity(),record=store.create(a);let m=new Match(record,r=>store.save(r)),serial=0;m.join(b);const send=(p,action,args={})=>m.command(p,{id:String(++serial),revision:m.record.revision,action,args});send(0,'ready',{deck:EXPANSION_DECK});send(1,'ready',{deck:ARTIFACT_DECKS[0]});const g=m.game;g.s.units=[];g.s.lane=0;g.s.turn=0;g.s.phase='action';g.s.lanes[0].mana=[50,50];spawn(g,'dark_willow',0,0);spawn(g,'dark_willow_bramble',0,1);const e=spawn(g,'pangolier',1,1),summon={uid:g.id(),k:'dark_willow_terrorize',lock:0},next={uid:g.id(),k:'grazing_shot',lock:0};g.s.players[0].hand=[summon,next];m.persist();send(0,'play',{handId:summon.uid,targets:[{lane:0,pos:1}]});m=new Match(store.load(record.code),r=>store.save(r));assert.equal(m.game.s.jex.length,1);send(1,'pass');send(0,'play',{handId:next.uid,targets:[e.uid]});assert(m.game.flag(m.game.get(e.uid),'flipped'));assert.equal(m.game.get(e.uid).damage,5);const seat=project(m.snapshot(1).state,1);assert.equal(seat.jex.length,0);assert(seat.units.find(u=>u.uid===e.uid).mods.some(m=>m.flipped));}finally{store.close();}});

test('Monkey King gains 1 energy per attack and Primed Strike is gated at 3, consumes 3 and stacks the soldier attack bonus',()=>{const g=arena(),mk=spawn(g,'monkey_king',0,0),e=spawn(g,'axe',1,0);g.buff(e,{attack:-8,health:40});for(const [before,after] of [[0,1],[1,2]]){assert.equal(mk.charges||0,before);g.battle(mk,e);assert.equal(mk.charges,after);}g.battle(mk,e);assert.equal(mk.charges,3);assert.equal(g.canActivate(0,mk.uid,'monkey_king'),'');const d=e.damage;g.activate(0,mk.uid,'monkey_king',[e.uid]);assert.equal(mk.charges,0);assert.equal(e.damage,d+Math.max(0,4-g.stats(e).armor));assert.equal(g.s.players[0].monkeyBonus,1);g.s.turn=0;assert.match(g.canActivate(0,mk.uid,'monkey_king'),/能量/);assert.throws(()=>g.activate(0,mk.uid,'monkey_king',[e.uid]),/能量/);});

test('Primed Strike bonus permanently buffs every future Monkey Soldier summon and stacks per cast',()=>{const g=arena(),mk=spawn(g,'monkey_king',0,0),e=spawn(g,'axe',1,0);const s1=spawn(g,'monkey_soldier',0,1);assert.equal(g.stats(s1).attack,1);mk.charges=3;g.activate(0,mk.uid,'monkey_king',[e.uid]);const s2=spawn(g,'monkey_soldier',0,2);assert.equal(g.stats(s2).attack,2);g.s.turn=0;mk.charges=3;g.activate(0,mk.uid,'monkey_king',[e.uid]);const s3=spawn(g,'monkey_soldier',0,3);assert.equal(g.stats(s3).attack,3);assert.equal(g.stats(s1).attack,1,'existing soldiers keep their spawn-time attack');assert.equal(g.stats(s2).attack,2);});

test('Nimble Shift card moves a chosen allied hero to an empty friendly slot and leaves a Monkey Soldier behind',()=>{const g=arena(),mk=spawn(g,'monkey_king',0,0),axe=spawn(g,'axe',0,1);cast(g,'tree_dance',[mk.uid,{lane:0,pos:2}]);assert.equal(mk.pos,2);const left=g.at(0,0,0);assert(left&&left.k==='monkey_soldier'&&g.card(left.k).token);assert.equal(g.stats(left).attack,1);cast(g,'tree_dance',[axe.uid,{lane:0,pos:3}]);assert.equal(axe.pos,3);assert(g.at(0,0,1).k==='monkey_soldier');const h={uid:g.id(),k:'tree_dance',lock:0};g.s.players[0].hand.push(h);const before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[mk.uid,{lane:0,pos:3}]));assert.deepEqual(g.s,before);});

test('Monkey Soldiers never attack buildings and still vanish after two unit attacks',()=>{const g=arena();const s=spawn(g,'monkey_soldier',0,1);const hp=g.s.lanes[0].towers[1].hp,f=g.combatForecast();assert.equal(f.tower[1],0);assert(!f.attacks.some(a=>a.unit===s.uid));g.combat();assert.equal(g.s.lanes[0].towers[1].hp,hp);assert(s.alive);assert.equal(s.attacks||0,0);const e=spawn(g,'axe',1,s.pos);g.buff(e,{attack:-8,health:40});g.battle(s,e);assert.equal(s.attacks,1);g.battle(s,e);assert(!s.alive);assert.equal(g.s.lanes[0].towers[1].hp,hp);});

test('Wukongs Command fills empty friendly slots with soldiers that expire after exactly two attacks with no bounty or death trigger',()=>{const g=arena();spawn(g,'monkey_king',0,0);spawn(g,'axe',0,3);cast(g,'monkey_king_command');const soldiers=g.all(0,0).filter(u=>u.k==='monkey_soldier');assert.deepEqual(soldiers.map(u=>u.pos).sort((a,b)=>a-b),[1,2,4]);const gold=g.s.players.map(p=>p.gold),blockers={};for(const s of soldiers){const b=spawn(g,'axe',1,s.pos);g.buff(b,{attack:-8,health:40});blockers[s.uid]=b;}for(let i=1;i<=2;i++){for(const s of soldiers){if(s.alive)g.battle(s,blockers[s.uid]);}for(const s of soldiers)if(s.alive)assert.equal(s.attacks,i);}assert.equal(g.all(0,0).filter(u=>u.k==='monkey_soldier').length,0);assert.equal(g.s.events.filter(e=>e.type==='expire').length,3);assert.equal(g.s.events.filter(e=>e.type==='death').length,0);assert.deepEqual(g.s.players.map(p=>p.gold),gold);});

test('monkey_king_command requires a Monkey King in lane and validates before spending mana',()=>{const g=arena();spawn(g,'axe',0,0);const h={uid:g.id(),k:'monkey_king_command',lock:0};g.s.players[0].hand.push(h);const before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[]),/齐天大圣/);assert.deepEqual(g.s,before);spawn(g,'monkey_king',0,2);cast(g,'monkey_king_command');assert.deepEqual(g.all(0,0).filter(u=>u.k==='monkey_soldier').map(u=>u.pos),[1,3]);});

test('Blast Off halves current health (rounded up) and Techies always keeps at least 1 health',()=>{const g=arena(),t=spawn(g,'techies',0,0),e=spawn(g,'axe',1,0);assert.equal(g.stats(t).hp,8);assert.equal(g.stats(e).hp,10);g.activate(0,t.uid,'techies',[e.uid]);assert.equal(e.damage,5,'half of 10 current hp');assert.equal(t.damage,5,'same amount back');assert.equal(g.stats(t).hp,3);g.s.turn=0;t.cooldowns={};e.damage=0;g.buff(e,{health:9});assert.equal(g.stats(e).hp,19);g.activate(0,t.uid,'techies',[e.uid]);assert.equal(e.damage,10,'ceil(19/2)=10');assert.equal(g.stats(t).hp,1,'self damage capped at hp-1');assert(t.alive);g.s.turn=0;t.cooldowns={};e.damage=0;g.activate(0,t.uid,'techies',[e.uid]);assert.equal(e.damage,10);assert.equal(g.stats(t).hp,1,'still pinned at 1');});

test('Blast Off respects cooldown, lane, ownership and rolls back fully on failure',()=>{const g=arena(),t=spawn(g,'techies',0,0),e=spawn(g,'axe',1,0),far=g.spawn('melee_creep',1,1,0);t.cooldowns.techies=2;assert.match(g.canActivate(0,t.uid,'techies'),/冷却/);assert.throws(()=>g.activate(0,t.uid,'techies',[e.uid]),/冷却/);g.get(t.uid).cooldowns={};assert.throws(()=>g.activate(0,t.uid,'techies',[far.uid]),/战线/);const before=clone(g.s);assert.throws(()=>g.activate(1,t.uid,'techies',[e.uid]));assert.deepEqual(g.s,before);g.buff(g.get(t.uid),{stun:1},'round');assert.match(g.canActivate(0,t.uid,'techies'),/无法使用/);});

test('Proximity Mines plant under an allied unit, stay hidden and reject stacking',()=>{const g=arena(),t=spawn(g,'techies',0,0),u=spawn(g,'melee_creep',0,1);cast(g,'proximity_mines',[u.uid]);assert.equal(g.s.mines.length,1);const m=g.s.mines[0];assert.equal(m.owner,0);assert.equal(m.unit,u.uid);const ev=g.s.events.find(e=>e.type==='mine-summon');assert(ev&&ev.secret===0,'placement event is owner-only');const h={uid:g.id(),k:'proximity_mines',lock:0};g.s.players[0].hand.push(h);g.s.turn=0;const before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[u.uid]),/感应地雷|Proximity Mine/);assert.deepEqual(g.s,before);const enemy=spawn(g,'melee_creep',1,2);assert.throws(()=>g.play(0,h.uid,[enemy.uid]),/阵营/);assert.equal(g.s.mines.length,1);});

test('mine detonates when its unit is attacked in battle, hurting adjacent enemies only',()=>{const g=arena();spawn(g,'techies',0,0);const u=spawn(g,'melee_creep',0,1),a=spawn(g,'axe',1,1),near=spawn(g,'melee_creep',1,2),far=spawn(g,'melee_creep',1,5);cast(g,'proximity_mines',[u.uid]);g.buff(a,{attack:-6,health:30});g.battle(a,u);assert.equal(g.s.mines.length,0,'mine consumed');assert.equal(a.damage,6,'8 blast minus 2 armor');assert.equal(near.damage,8);assert.equal(far.damage,0,'out of adjacency');assert(g.s.events.some(e=>e.type==='mine'));});

test('mine detonates on combat-phase attacks and after enemy targeted spells, but never on friendly spells',()=>{const g=arena();spawn(g,'techies',0,0);const u=spawn(g,'axe',0,1),a=spawn(g,'sorla_khan',1,1);cast(g,'proximity_mines',[u.uid]);cast(g,'combat_training',[u.uid]);assert.equal(g.s.mines.length,1,'friendly spell does not trigger');cast(g,'no_accident',[u.uid],1);assert.equal(g.s.mines.length,0,'enemy spell detonates');assert.equal(a.damage,8,'adjacent enemy takes the blast');assert.equal(u.damage,3-2,'no_accident through armor');
 const g2=arena();spawn(g2,'techies',0,0);const u2=spawn(g2,'melee_creep',0,1),a2=spawn(g2,'axe',1,1);cast(g2,'proximity_mines',[u2.uid]);g2.buff(a2,{health:30});g2.combat();assert.equal(g2.s.mines.length,0,'combat attack detonates');assert.equal(a2.damage,6,'blast through armor');assert(!u2.alive,'mined creep still dies to the attacker');});

test('mine owner may detonate manually, which spends the action; carrier death removes the mine silently',()=>{const g=arena();spawn(g,'techies',0,0);const u=spawn(g,'melee_creep',0,1),e=spawn(g,'axe',1,1);cast(g,'proximity_mines',[u.uid]);const uid=g.s.mines[0].uid;assert.throws(()=>g.detonateMine(1,uid),/感应地雷|Mine/);g.s.turn=0;g.detonateMine(0,uid);assert.equal(g.s.mines.length,0);assert.equal(e.damage,6,'8 blast minus 2 armor');assert.equal(g.s.turn,1,'manual detonation passes the turn');
 const g2=arena();spawn(g2,'techies',0,0);const u2=spawn(g2,'melee_creep',0,1),e2=spawn(g2,'axe',1,2);cast(g2,'proximity_mines',[u2.uid]);g2.condemn(u2);g2.sweep();assert(!u2.alive);assert.equal(g2.s.mines.length,0,'mine removed with carrier');assert.equal(e2.damage,0,'no detonation on untargeted death');});

test('Reactive Tazer disarms one ally and up to two enemies in lane, seeded, and detonates a mine on the disarmed ally',()=>{const g=arena();const u=spawn(g,'melee_creep',0,0),t=spawn(g,'techies',0,1);cast(g,'proximity_mines',[u.uid]);const e1=spawn(g,'axe',1,0),e2=spawn(g,'melee_creep',1,1),e3=spawn(g,'melee_creep',1,5);g.buff(e2,{health:30});const pick=g.pick.bind(g),shuf=g.shuffle.bind(g);g.pick=a=>a[0];g.shuffle=a=>[...a];cast(g,'reactive_tazer');assert(g.flag(u,'disarm'),'first ally disarmed');assert(g.flag(e1,'disarm')&&g.flag(e2,'disarm'),'two enemies disarmed');assert(!g.flag(e3,'disarm'));assert.equal(g.s.mines.length,0,'mine on disarmed ally detonates');assert(g.s.events.some(e=>e.type==='mine'&&e.cause==='tazer'));g.pick=pick;g.shuffle=shuf;
 const g2=arena();spawn(g2,'melee_creep',0,0);const t2=spawn(g2,'techies',0,1);const e=spawn(g2,'axe',1,0);g2.buff(e,{health:30});g2.pick=()=>t2;g2.shuffle=a=>[...a];cast(g2,'reactive_tazer');assert(g2.flag(t2,'disarm'));assert(g2.flag(e,'disarm'));assert.equal(g2.s.mines?.length||0,0);assert(!g2.s.events.some(e2=>e2.type==='mine'),'no mine -> no detonation');});

test('mines survive save/load and stay hidden from the opposing seat in online snapshots',()=>{const {Store}=require('../server/store.cjs'),{Match}=require('../server/match.cjs'),store=new Store(':memory:');try{const a=store.identity(),b=store.identity(),record=store.create(a);let m=new Match(record,r=>store.save(r)),serial=0;m.join(b);const send=(p,action,args={})=>m.command(p,{id:String(++serial),revision:m.record.revision,action,args});send(0,'ready',{deck:MK_DECK});send(1,'ready',{deck:ARTIFACT_DECKS[0]});const g=m.game;g.s.units=[];g.s.lane=0;g.s.turn=0;g.s.phase='action';g.s.lanes[0].mana=[50,50];const t=spawn(g,'techies',0,0),u=spawn(g,'melee_creep',0,1),e=spawn(g,'axe',1,1);g.buff(e,{health:30});const mine={uid:g.id(),k:'proximity_mines',lock:0};g.s.players[0].hand=[mine];m.persist();send(0,'play',{handId:mine.uid,targets:[u.uid]});assert.equal(m.game.s.mines.length,1);m=new Match(store.load(record.code),r=>store.save(r));assert.equal(m.game.s.mines.length,1,'mine survives persistence');const hostile=m.snapshot(1);assert.equal(hostile.state.mines.length,0,'opponent cannot see the mine');assert(!hostile.state.log.some(x=>x.type==='mine-summon'),'hidden event stays out of the log');const own=m.snapshot(0);assert.equal(own.state.mines.length,1);const seat=project(own.state,0);assert.equal(seat.mines.length,1);send(1,'pass');send(0,'detonate',{mine:m.game.s.mines[0].uid});assert.equal(m.game.s.mines.length,0);assert(m.game.get(e.uid).damage>=8-2);assert(m.snapshot(1).state.log.some(x=>x.type==='mine'),'detonation is public');}finally{store.close();}});
