const assert=require('node:assert/strict');
const fs=require('node:fs');
const cards=require('../dist/cards.json');
const {Game,clone}=require('../dist/engine.js');
require('../dist/effects.js');require('../dist/decks.js');
const decks=global.ARTIFACT_DECKS;
let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name);}catch(e){console.error('FAIL',name,e);process.exitCode=1;}}
function fresh(){const g=new Game(cards);g.newGame(decks[0],decks[1],1234);return g;}
function arena(){const g=fresh();g.s.units=[];g.s.lane=0;g.s.turn=0;g.s.phase='action';g.s.events=[];for(let p=0;p<2;p++){g.s.players[p].hand=[];g.s.players[p].gold=30;g.s.lanes[0].mana[p]=50;['axe','drow_ranger','zeus','phantom_assassin'].forEach((k,pos)=>g.spawn(k,p,0,pos));g.spawn('melee_creep',p,0,4);g.spawn('zeus',p,1,0);g.spawn('meepo',p,2,0);for(const u of g.all(p,0))if(u.hero)u.items.Weapon={k:'short_sword',growth:0};g.imps(p,0).push({uid:g.id(),k:'mist_of_avernus',charges:0,cooldown:0});}return g;}
function hand(g,k){const h={uid:g.id(),k,lock:0};g.s.players[0].hand.push(h);return h;}
function invariants(g){for(const u of g.all()){const st=g.stats(u);for(const v of Object.values(st))assert(typeof v==='boolean'||Number.isFinite(v),'nonfinite stat '+u.k);assert(st.hp>=0);assert(u.lane>=0&&u.lane<3);assert(g.all(u.owner,u.lane).filter(v=>v.pos===u.pos).length===1,'duplicate slot');}for(const p of g.s.players)assert(p.gold>=0);for(const l of g.s.lanes)l.mana.forEach(n=>assert(Number.isFinite(n)&&n>=0));}
test('313 entries, 51 heroes, unique keys and complete local art',()=>{assert.equal(cards.length,313);assert.equal(cards.filter(c=>c.type==='Hero').length,51);assert.equal(new Set(cards.map(c=>c.key)).size,313);for(const c of cards){assert(fs.existsSync(require('node:path').join(__dirname,'../dist',c.art)));if(c.signature)assert(cards.some(v=>v.key===c.signature));assert(!c.text.includes('{s:'));}for(const d of decks)assert.deepEqual(fresh().validateDeck(d),[]);});
test('all spells have explicit handlers',()=>{for(const c of cards.filter(c=>c.type==='Spell'))assert(ArtifactEngine.SPELL_KEYS.includes(c.key),c.key);});
test('armor, negative armor and piercing damage',()=>{const g=arena(),u=g.all(0,0)[0];g.damage(u,5);assert.equal(u.damage,3);g.damage(u,5,true);assert.equal(u.damage,8);u.damage=0;g.buff(u,{armor:-5});g.damage(u,2);assert.equal(u.damage,5);});
test('immunity prevents damage; death shield prevents one condemnation',()=>{const g=arena(),u=g.all(0,0)[0];g.buff(u,{immune:1},'round');g.damage(u,30);assert.equal(u.damage,0);g.buff(u,{deathShield:1},'round');g.condemn(u);g.sweep();assert(u.alive);assert.equal(g.stats(u).hp,1);g.condemn(u);g.sweep();assert(!u.alive);});
test('combat damage is simultaneous and both creep bounties paid',()=>{const g=arena();g.s.units=[];const a=g.spawn('zombie',0,0,0),b=g.spawn('zombie',1,0,0);const gold=g.s.players.map(p=>p.gold);g.combat();assert(!a.alive&&!b.alive);assert.equal(g.s.players[0].gold,gold[0]+1);assert.equal(g.s.players[1].gold,gold[1]+1);});
test('40 HP tower replaces with 80 HP ancient without overflow',()=>{const g=fresh();g.towerDamage(1,0,100,true);g.checkWin();assert.equal(g.s.lanes[0].towers[1].hp,80);assert(g.s.lanes[0].towers[1].fallen);assert.equal(g.s.winner,null);g.towerDamage(1,0,80,true);g.checkWin();assert.equal(g.s.winner,0);});
test('destroying two enemy towers wins',()=>{const g=fresh();g.towerDamage(1,0,40,true);g.towerDamage(1,2,40,true);g.checkWin();assert.equal(g.s.winner,0);});
test('consecutive passes resolve lane and preserve first passer initiative',()=>{const g=fresh();g.s.units=[];g.pass(0);assert.equal(g.s.turn,1);assert.equal(g.s.passes,1);g.pass(1);assert.equal(g.s.lane,1);assert.equal(g.s.turn,0);assert.equal(g.s.phase,'action');});
test('invalid target rolls back mana, hand and random state',()=>{const g=arena(),h=hand(g,'duel'),before=clone(g.s);assert.throws(()=>g.play(0,h.uid,[999999,1]));assert.deepEqual(g.s,before);});
test('same-lane color requirement cannot be bypassed by another lane',()=>{const g=arena();for(const u of g.all(0,0))if(g.card(u.k).color==='Blue')u.alive=false;const h=hand(g,'lightning_strike');assert.match(g.canPlay(0,h),/蓝色英雄/);});
test('silenced hero cannot cast colored cards',()=>{const g=arena();for(const u of g.all(0,0))g.buff(u,{silence:1},'round');assert.match(g.canPlay(0,hand(g,'lightning_strike')),/蓝色英雄/);});
test('cross-lane Assassinate damages its selected target',()=>{const g=arena(),target=g.all(1,1)[0];g.play(0,hand(g,'assassinate').uid,[target.uid]);assert(!g.get(target.uid).alive);assert.equal(g.s.turn,1);});
test('Get initiative card keeps action priority',()=>{const g=arena(),u=g.all(0,0)[0];g.play(0,hand(g,'fight_through_the_pain').uid,[u.uid]);assert.equal(g.s.turn,0);assert.equal(g.s.initiative,0);});
test('Cheating Death is an active shield, with cooldown',()=>{const g=arena(),i={uid:g.id(),k:'cheating_death',cooldown:0,charges:0};g.imps(0,0).push(i);const u=g.all(0,0)[0];g.activate(0,i.uid,i.k,[u.uid]);assert(g.flag(u,'deathShield'));assert.equal(i.cooldown,1);});
test('Shop Deed is consumed and makes future secret items free',()=>{const g=arena();g.play(0,hand(g,'shop_deed').uid,[]);assert(g.s.players[0].freeShop);assert(!g.all(0).some(u=>u.items.Deed));});
test('shop debits once, deck refills, consumable cannot be bought twice',()=>{const g=fresh();g.s.phase='shop';g.openShop();g.s.players[0].gold=100;const pl=g.s.players[0],k=pl.shop.deck,cost=g.card(k).gold,n=pl.itemDeck.length;g.buy(0,'deck');assert.equal(pl.gold,100-cost);assert.equal(pl.itemDeck.length,n-1);assert.equal(pl.hand.at(-1).k,k);g.buy(0,'consumable');assert.throws(()=>g.buy(0,'consumable'));});
test('hero death retains permanent upgrades and equipment; misses next round',()=>{const g=arena(),u=g.all(0,0)[0];g.buff(u,{attack:4});g.buff(u,{armor:2},'round');g.condemn(u);g.sweep();assert(!u.alive);assert.equal(u.readyRound,3);assert.equal(u.items.Weapon.k,'short_sword');assert(!u.mods.some(m=>m.until==='round'));assert(u.mods.some(m=>m.attack===4));g.s.round=2;assert(!g.ready(0).includes(u));g.s.round=3;g.s.phase='deploy';assert(g.ready(0).includes(u));g.deploy(u.uid,2);assert(u.alive);assert.equal(u.damage,0);});
test('item replacement preserves one slot and changes attributes',()=>{const g=arena(),u=g.all(0,0)[0],before=g.stats(u).attack;g.play(0,hand(g,'broadsword').uid,[u.uid]);assert.equal(g.stats(u).attack,before+2);assert.equal(Object.keys(u.items).length,1);});
test('Enough Magic resolves the lane after on-cast effects',()=>{const g=arena();g.play(0,hand(g,'enough_magic').uid,[]);assert.equal(g.s.lane,1);assert.equal(g.s.phase,'action');assert(!g.s.pendingCombat);});
test('seeded state roundtrips and produces deterministic decisions',()=>{const g=fresh(),h=new Game(cards);h.s=clone(g.s);assert.deepEqual(g.bestAction(0),h.bestAction(0));assert.deepEqual(g.s,h.s);});
test('every spell and consumable can execute a valid representative cast',()=>{const failures=[];for(const c of cards.filter(c=>c.type==='Spell'||c.type==='Item'&&['Consumable','Deed'].includes(c.itemType))){const g=arena();if(c.requiredHero)g.spawn(c.requiredHero,0,0,7);hand(g,'foresight');const h=hand(g,c.key);h.charges=3;const snapshot=clone(g.s);let ok=false,last='no targets';for(const t of g.candidateTargets(c.key,0)){g.s=clone(snapshot);try{g.play(0,h.uid,t);invariants(g);ok=true;break;}catch(e){last=e.message;}}if(!ok)failures.push(c.key+': '+last);}assert.deepEqual(failures,[]);});
test('every activated ability has an executable representative case',()=>{const failures=[];for(const c of cards.filter(c=>c.abilities.length)){const g=arena();let u;if(c.type==='Improvement'){u={uid:g.id(),k:c.key,cooldown:0,charges:3};g.imps(0,0).push(u);}else if(c.type==='Item'){u=g.all(0,0)[0];u.items[c.itemType]={k:c.key,charges:2};}else u=g.spawn(c.key,0,0,6);
 // Align targets for abilities that explicitly operate on blockers/neighbors.
 if(['ravenhook','ravenous_mass','bracers_of_sacrifice'].includes(c.key)){u.pos=7;g.spawn('axe',1,0,7).items.Weapon={k:'broadsword'};g.spawn('melee_creep',0,0,8);}
 if(c.key==='demagicking_maul'){u.pos=8;}if(c.key==='monkey_king'){u.charges=3;}if(c.key==='unsupervised_artillery'){for(const v of g.all(1,0)){if(!g.at(0,0,v.pos))g.spawn('melee_creep',0,0,v.pos);v.target=g.at(0,0,v.pos).uid;}}
 if(u.cooldowns)u.cooldowns={};const snapshot=clone(g.s);let ok=false,last='no targets';for(const t of g.candidateTargets(c.key,0,u)){g.s=clone(snapshot);try{g.activate(0,u.uid,c.key,t);invariants(g);ok=true;break;}catch(e){last=e.message;}}if(!ok)failures.push(c.key+': '+last);}assert.deepEqual(failures,[]);});
test('hero abilities start on cooldown; reserve cooldown ticks before deployment',()=>{const g=fresh(),u=g.s.units.find(u=>u.k==='sniper');assert.equal(u.cooldowns.sniper,3);g.s.phase='shop';g.openShop();g.startRound();assert.equal(u.cooldowns.sniper,2);});
if(!process.exitCode)console.log(`${passed} suites passed.`);
