const assert=require('node:assert/strict'),cards=require('../dist/cards.json');
const {Game,clone}=require('../dist/engine.js');require('../dist/effects.js');require('../dist/decks.js');require('../dist/feedback.js');
function arena(){const g=new Game(cards);g.newGame(global.ARTIFACT_DECKS[0],global.ARTIFACT_DECKS[1],1234);g.s.units=[];g.s.events=[];g.s.lane=0;for(let p=0;p<2;p++){g.s.players[p].hand=[];g.s.lanes[0].mana[p]=50;g.spawn('axe',p,0,0);g.spawn('zeus',p,0,1);g.spawn('drow_ranger',p,0,2);}return g;}
function play(g,k,target,p=0){g.s.turn=p;const h={uid:g.id(),k,lock:0};g.s.players[p].hand.push(h);g.play(p,h.uid,target);return g.s.events.find(e=>e.type==='card');}
let g=arena(),u=g.all(0,0)[0],e=play(g,'defensive_stance',[u.uid]);assert.equal(e.targets[0].name,'斧王');assert(e.outcomes.some(o=>o.uid===u.uid&&o.changes.includes('护甲+3')));console.log('PASS non-damage buff names target and armor result');
g=arena();u=g.all(0,0)[0];e=play(g,'frostbite',[u.uid],1);assert.equal(e.owner,1);assert(e.outcomes.find(o=>o.uid===u.uid).changes.includes('缴械'));assert(e.text.includes('天辉·斧王'));console.log('PASS enemy cast retains faction and disabling effect');
g=arena();u=g.all(1,0)[1];u.damage=6;e=play(g,'frostbite',[u.uid]);assert(!u.alive);assert.equal(e.targets[0].lane,0);assert(e.outcomes.find(o=>o.uid===u.uid).changes.includes('阵亡'));assert(e.outcomes.find(o=>o.uid===u.uid).changes.some(c=>c.startsWith('伤害')));console.log('PASS lethal spell preserves target identity after death');
g=arena();u=g.spawn('lion',1,0,3);u.cooldown=0;u.cooldowns={lion:0};g.s.turn=1;g.activate(1,u.uid,'lion',[g.all(0,0)[1].uid]);e=g.s.events.find(e=>e.type==='ability');assert.equal(e.owner,1);assert.equal(e.source.name,'莱恩');assert(e.label);assert(e.outcomes.length);console.log('PASS enemy active ability captures source, ability name and damage target');
g=arena();u=g.all(0,0)[0];e=play(g,'short_sword',[u.uid]);assert(e.outcomes.find(o=>o.uid===u.uid).changes.includes('装备更新'));console.log('PASS equipment gives explicit feedback');
g=arena();const state=clone(g.s);assert.throws(()=>g.play(0,-1,[]));assert.deepEqual(g.s,state);console.log('PASS invalid action preserves game state');
