const assert=require('node:assert/strict');const cards=require('../dist/cards.json');const {Game,clone}=require('../dist/engine');require('../dist/effects');require('../dist/decks');const skills=require('../dist/hero-skills');let n=0;function test(name,fn){fn();console.log('PASS',name);n++;}function arena(){const g=new Game(cards);g.newGame(global.ARTIFACT_DECKS[0],global.ARTIFACT_DECKS[1],42);g.s.units=[];g.s.events=[];g.s.lane=0;g.s.turn=0;g.s.phase='action';return g;}
test('48 Classic and 3 expansion heroes are explicitly classified, with two Meepo/Monkey King abilities and four intentional exceptions',()=>{const heroes=cards.filter(c=>c.type==='Hero');assert.equal(Object.keys(skills.all).length,51);for(const c of heroes){const a=skills.list(c.key);assert(a.length);for(const s of a){assert(s.name&&s.description);assert(['active','passive','none'].includes(s.type));if(s.type==='active')assert(c.abilities.some(x=>(x.key||c.key)===(s.k||s.key||c.key)&&x.cooldown===s.cooldown));}}assert.equal(skills.list('meepo').length,2);assert.equal(skills.list('monkey_king').length,2);assert.deepEqual(heroes.filter(c=>skills.get(c.key).type==='none').map(c=>c.key).sort(),['axe','keefe_the_bold','magnus','mazzie']);});
test('Luna automatically deals piercing damage and charges exactly three random Eclipse copies in current Classic',()=>{const g=arena(),u=g.spawn('luna',0,0,0),enemy=g.spawn('axe',1,0,0);g.s.players[0].hand=Array.from({length:5},()=>({k:'eclipse',uid:g.id(),charges:0}));g.s.players[0].deck=[];g.beforeAction(0);assert.equal(enemy.damage,1);assert.equal(g.s.players[0].hand.reduce((n,h)=>n+h.charges,0),3);assert.equal(g.abilities(u).length,0);assert(g.s.events.some(e=>e.type==='passive'&&e.unit===u.uid&&e.target===enemy.uid));});
test('silenced Luna neither damages nor charges',()=>{const g=arena(),u=g.spawn('luna',0,0,0),e=g.spawn('axe',1,0,0);g.buff(u,{silence:1},'round');g.beforeAction(0);assert.equal(e.damage,0);});
test('Timbersaw gains armor per attacker and reduces each attacker armor; silence removes both',()=>{const g=arena(),u=g.spawn('timbersaw',0,0,0),a=g.spawn('axe',1,0,0),b=g.spawn('axe',1,0,1);b.target=u.uid;assert.equal(g.stats(u).armor,2);assert.equal(g.stats(a).armor,1);assert.equal(g.stats(b).armor,1);g.buff(u,{silence:1},'round');assert.equal(g.stats(u).armor,0);assert.equal(g.stats(a).armor,2);});
test('Viper defensive passive triggers even if attacking unit is silenced',()=>{const g=arena(),u=g.spawn('viper',0,0,0),a=g.spawn('axe',1,0,0);g.buff(a,{silence:1},'round');g.onBattleHit(a,u);assert.equal(g.stats(a).attack,5);g.buff(u,{silence:1},'round');g.onBattleHit(a,u);assert.equal(g.stats(a).attack,5);});
test('active skill availability is read-only, respects cooldown and target availability',()=>{const g=arena(),u=g.spawn('sniper',0,0,0);const before=clone(g.s);assert.match(g.canActivate(0,u.uid,u.k),/冷却/);assert.deepEqual(g.s,before);u.cooldowns.sniper=0;assert.equal(g.canActivate(0,u.uid,u.k),'');g.buff(u,{silence:1},'round');assert.match(g.canActivate(0,u.uid,u.k),/无法/);const p=g.spawn('pugna',0,0,1);p.cooldowns.pugna=0;assert.match(g.canActivate(0,p.uid,p.k),/没有强化/);});
test('global aura affects other lanes, adjacent aura excludes self',()=>{const g=arena(),d=g.spawn('drow_ranger',0,0,0),a=g.spawn('axe',0,1,0),t=g.spawn('treant_protector',0,1,1);assert.equal(g.stats(a).attack,7);assert.equal(g.stats(d).attack,3);assert.equal(g.stats(a).armor,4);assert.equal(g.stats(t).armor,0);});
test('Ursa, Bristleback and Necrophos persist their triggered stat modifications',()=>{const g=arena(),u=g.spawn('ursa',0,0,0),b=g.spawn('bristleback',0,0,1),n=g.spawn('necrophos',0,0,2),e=g.spawn('axe',1,0,1);g.onBattleHit(u,e);assert.equal(g.stats(e).armor,1);g.condemn(e);g.sweep();assert.equal(g.stats(b).armor,2);assert.equal(g.stats(n).health,7);});
test('spell passives preserve card event and generate separate source-labelled feedback',()=>{const g=arena(),z=g.spawn('zeus',0,0,0),e=g.spawn('axe',1,0,0);g.afterCard(0,g.card('foresight'));assert.equal(e.damage,1);assert(g.s.events.some(x=>x.type==='passive'&&x.unit===z.uid));});
test('death passives follow actual diagonal blockers and do not trigger for a different target',()=>{const g=arena(),b=g.spawn('bristleback',0,0,0),blood=g.spawn('bloodseeker',0,0,1),e=g.spawn('axe',1,0,0),other=g.spawn('axe',1,0,1);b.target=other.uid;blood.target=e.uid;blood.damage=3;g.condemn(e);g.sweep();assert.equal(g.stats(b).armor,0);assert.equal(blood.damage,0);g.condemn(other);g.sweep();assert.equal(g.stats(b).armor,2);});
console.log(n+' hero skill suites passed.');
