/* Browser network adapter contract, no network or local user data. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(){const values=new Map(),messages={},leave=[];let sent;const room={onMessage:(k,fn)=>messages[k]=fn,onError:()=>{},onLeave:fn=>leave.push(fn),send:(type,data)=>{sent={type,data};},leave:()=>leave.forEach(fn=>fn())};const context={window:{},localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},location:{origin:'http://example.test:8787',search:''},URLSearchParams,crypto:{getRandomValues:a=>{a.fill(1);return a;}},setTimeout,clearTimeout,fetch:async()=>({ok:true,json:async()=>({token:'anonymous',rooms:[]})}),Colyseus:{Client:class{async joinOrCreate(type,args){assert.equal(type,'battle');assert.equal(args.token,'anonymous');return room;}}}};context.window.Colyseus=context.Colyseus;vm.runInNewContext(fs.readFileSync('dist/online-client.js','utf8'),context);return {net:context.window.ArtifactOnline,messages,room,values,getSent:()=>sent};}
test('connect stores anonymous identity, restores seat and command carries revision',async()=>{const f=fixture(),joining=f.net.connect('abc123');await new Promise(r=>setImmediate(r));const snapshot={code:'ABC123',revision:4,seat:1,players:[],status:'battle',state:{}};f.messages.snapshot(snapshot);assert.equal((await joining).seat,1);assert.equal(f.net.getStatus(),'connected');assert.equal(f.values.get('artifact.online.room'),'ABC123');const result=f.net.command('pass');assert.equal(f.getSent().data.revision,4);assert.equal(f.getSent().data.action,'pass');f.messages.snapshot({...snapshot,revision:5,ack:'01010101010101010101010101010101'});assert.equal((await result).revision,5);f.net.disconnect();});
test('server command rejection rejects pending promise without applying stale state',async()=>{const f=fixture(),joining=f.net.connect('ABC123');await new Promise(r=>setImmediate(r));f.messages.snapshot({code:'ABC123',revision:3});await joining;const p=f.net.command('ready');f.messages.error({id:'01010101010101010101010101010101',message:'牌组无效',revision:3});await assert.rejects(p,/牌组无效/);assert.equal(f.net.getSnapshot().revision,3);f.net.disconnect();});
test('disconnect rejects outstanding operation; offline never sends commands',async()=>{const f=fixture(),joining=f.net.connect('ABC123');await new Promise(r=>setImmediate(r));f.messages.snapshot({code:'ABC123',revision:1});await joining;const p=f.net.command('pass');f.net.disconnect();await assert.rejects(p,/已离开房间/);await assert.rejects(f.net.command('pass'),/重新连接/);});

test('a replacement page stops automatic reconnection and rejects pending action',async()=>{const f=fixture(),joining=f.net.connect('ABC123');await new Promise(r=>setImmediate(r));f.messages.snapshot({code:'ABC123',revision:1});await joining;const p=f.net.command('pass');f.messages.replaced({});await assert.rejects(p,/其他页面/);assert.equal(f.net.getStatus(),'replaced');await assert.rejects(f.net.command('pass'),/重新连接/);});

test('spectator cannot submit commands or overwrite last player room',async()=>{const f=fixture();f.values.set('artifact.online.room','PLAYER');const joining=f.net.connect('WATCH1',{spectate:true});await new Promise(r=>setImmediate(r));f.messages.snapshot({code:'WATCH1',revision:1,seat:'spectator',spectator:true});await joining;assert.equal(f.values.get('artifact.online.room'),'PLAYER');await assert.rejects(f.net.command('concede'),/观战/);assert.equal(f.getSent(),undefined);f.net.disconnect();});
