const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const root={};root.window=root;vm.runInNewContext(fs.readFileSync('dist/scene.js','utf8'),root);const kind=root.ArtifactScene.effectKind;
const {Game}=require('../dist/engine.js');require('../dist/effects.js');require('../dist/decks.js');require('../dist/feedback.js');const cards=require('../dist/cards.json'),byKey=Object.fromEntries(cards.map(c=>[c.key,c]));
function arena(){const g=new Game(cards);g.newGame(ARTIFACT_DECKS[0],ARTIFACT_DECKS[1],1234);g.s.units=[];g.s.lane=0;g.s.turn=0;g.s.lanes[0].mana[0]=50;g.spawn('axe',0,0,0);g.spawn('zeus',0,0,1);g.spawn('axe',1,0,0);g.spawn('zeus',1,0,1);g.s.events=[];return g;}
function play(g,k,targets){const h={uid:g.id(),k,lock:0};g.s.players[0].hand=[h];g.play(0,h.uid,targets);return g.s.events.find(e=>e.type==='card');}
let g=arena(),u=g.all(0,0)[0];u.damage=5;let cast=play(g,'healing_salve',[u.uid]);assert.equal(kind(byKey[cast.card],cast,cast.outcomes.find(o=>o.uid===u.uid)),'healing');console.log('PASS healing restores health and selects a healing effect');
g=arena();u=g.all(0,0)[0];cast=play(g,'short_sword',[u.uid]);assert.equal(kind(byKey[cast.card],cast,cast.outcomes.find(o=>o.uid===u.uid)),'equip');console.log('PASS equipment uses its own effect instead of an attack');
g=arena();cast=play(g,'bronze_legionnaire',[{lane:0,pos:2}]);assert.equal(kind(byKey[cast.card],cast,cast.outcomes.find(o=>o.changes.includes('进入战场'))),'summon');console.log('PASS newly placed units receive summon effects');
g=arena();u=g.all(0,0)[0];cast=play(g,'defensive_stance',[u.uid]);assert.equal(kind(byKey[cast.card],cast,cast.outcomes.find(o=>o.uid===u.uid)),'blessing');g=arena();cast=play(g,'sow_venom',[]);assert(cast.outcomes.some(o=>kind(byKey[cast.card],cast,o)==='summon'));const damage=cast.outcomes.find(o=>o.owner===1&&o.changes.some(c=>c.includes('伤害')));assert(damage);assert.equal(kind(byKey[cast.card],cast,damage),'strike');console.log('PASS allied summon and simultaneous Zeus passive damage have different effects');
assert.equal(kind({key:'frostbite'},{type:'card'},{changes:['缴械']}),'frost');assert.equal(kind({key:'gust'},{type:'card'},{changes:['沉默']}),'binding');console.log('PASS control effects remain distinct from attacks');
