'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),express=require('express');
const {Store}=require('./store.cjs'),{adminToken,mountAdmin}=require('./admin.cjs');
(async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'artifact-admin-')),store=new Store(':memory:');let server;try{
 const token=adminToken(path.join(directory,'admin-token'));assert.equal(adminToken(path.join(directory,'admin-token')),token);assert.equal(token.length,64);assert.throws(()=>adminToken('', 'short'));
 const a=store.identity(),b=store.identity();const active=store.create(a);active.status='battle';active.seats[1]={token:b,deck:{name:'Opponent',heroes:['axe']},ready:true};active.state={round:3,lane:1,phase:'action',winner:null};store.save(active);
 for(let i=0;i<23;i++){const r=store.create(a);r.status='finished';r.state={round:5,lane:2,phase:'ended',winner:i%2};store.save(r);}
 const app=express();app.use(express.json());let now=100000;const liveRooms=new Map([[active.code,{sessions:new Map([['session',0]]),match:{record:active},connected:()=>[true,false]}]]);mountAdmin(app,{store,liveRooms,token,clock:()=>now});app.use(express.static(path.join(__dirname,'../dist')));server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));const base='http://127.0.0.1:'+server.address().port;
 assert.equal((await fetch(base+'/_admin/wrong')).status,404);assert.equal((await fetch(base+'/_admin/wrong/data')).status,404);assert.equal((await fetch(base+'/_admin/'+token)).status,200);assert.equal((await fetch(base+'/admin.html')).status,404);
 const send=body=>fetch(base+'/api/online/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});assert.equal((await send({token:'bad'})).status,401);assert.equal((await send({token:b,page:'secret-invalid'})).status,400);assert.equal((await send({token:b,page:'campaign'})).status,204);
 let res=await fetch(base+'/_admin/'+token+'/data?status=battle'),data=await res.json();assert.equal(res.headers.get('cache-control'),'no-store');assert.equal(data.online.users,2);assert.equal(data.online.roomUsers,1);assert.equal(data.total,1);assert.deepEqual(data.rooms[0].connected,[true,false]);assert.equal(data.rooms[0].players[1].heroes[0],'斧王');assert(!JSON.stringify(data).includes(a));assert(!JSON.stringify(data).includes(b));assert.equal(data.rooms[0].round,3);assert.equal(data.online.visitors.find(v=>v.page==='campaign').lastSeen,now);assert(data.online.visitors.every(v=>/^[a-f0-9]{12}$/.test(v.id)));assert(!JSON.stringify(data).includes(token));
 data=await (await fetch(base+'/_admin/'+token+'/data?status=finished&page=2')).json();assert.equal(data.total,23);assert.equal(data.rooms.length,3);assert.equal(data.counts.battle,1);assert.equal(data.counts.finished,23);
 now+=76000;data=await (await fetch(base+'/_admin/'+token+'/data')).json();assert.equal(data.online.users,1);assert.equal(data.online.recentVisitors,0);liveRooms.clear();data=await (await fetch(base+'/_admin/'+token+'/data')).json();assert.equal(data.online.users,0);
 console.log('PASS administrator secret route, persistence, no credential leak, live connections, presence expiry and paginated history');
 }finally{if(server)await new Promise(resolve=>server.close(resolve));store.close();fs.rmSync(directory,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
