'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {mkdtempSync,rmSync}=require('node:fs'),{tmpdir}=require('node:os'),path=require('node:path');
const {Store}=require('./store.cjs'),{Matchmaker}=require('./matchmaking.cjs'),{Match}=require('./match.cjs');
require('../dist/decks.js');const deck=ARTIFACT_DECKS[0];
function fixture(filename=':memory:'){const store=new Store(filename);let time=100000;const clock=()=>time;let maker=new Matchmaker(store,{clock});const tokens=Array.from({length:4},()=>store.identity());return {store,tokens,clock,get maker(){return maker;},advance:ms=>time+=ms,reload:()=>maker=new Matchmaker(store,{clock}),call:(action,i,args)=>maker.request(action,tokens[i],args),close:()=>store.close()};}
function pair(f){f.call('join',0);f.call('join',1);f.advance(10000);return f.call('status',0);}
test('FIFO eligible players each wait ten seconds; lone queue remains until cancelled or heartbeat expires',()=>{const f=fixture();try{assert.equal(f.call('join',0).status,'queued');f.advance(5000);f.call('join',1);f.advance(4999);assert.equal(f.call('status',0).status,'queued');f.advance(1);assert.equal(f.call('status',0).status,'queued');f.advance(5000);assert.equal(f.call('status',0).status,'matched');assert.equal(f.call('status',1).matchId,f.call('status',0).matchId);assert.equal(f.store.rooms(f.tokens[0]).length,0,'no temporary rooms');f.call('join',2);for(let n=0;n<10;n++){f.advance(10000);assert.equal(f.call('status',2).status,'queued');}assert.equal(f.call('cancel',2).status,'idle');f.call('join',2);f.advance(15000);assert.equal(f.call('status',2).reason,'expired');}finally{f.close();}});
test('ready is explicit, validates deck, creates one battle with reserved seats and survives duplicate requests',()=>{const f=fixture();try{const pairState=pair(f),matchId=pairState.matchId;assert.equal(pairState.deadline,f.clock()+30000);assert.throws(()=>f.call('ready',0,{matchId,deck:{}}));assert.throws(()=>f.call('ready',0,{matchId:'old',deck}));assert.equal(f.call('ready',0,{matchId,deck}).mineReady,true);assert.equal(f.call('ready',0,{matchId,deck}).status,'matched');assert.equal(f.store.rooms(f.tokens[0]).length,0);const result=f.call('ready',1,{matchId,deck});assert.equal(result.status,'battle');assert.equal(f.call('ready',0,{matchId,deck}).code,result.code);assert.equal(f.call('cancel',0,{matchId}).code,result.code);assert.equal(f.call('join',0).code,result.code);assert.equal(f.store.rooms(f.tokens[0]).length,1);const record=f.store.load(result.code);assert.equal(record.status,'battle');assert.deepEqual(record.seats.map(s=>s.token),f.tokens.slice(0,2));assert.throws(()=>new Match(record,()=>{}).join(f.tokens[2]),/满/);}finally{f.close();}});
test('thirty-second timeout requeues only ready active player and resets ten-second eligibility',()=>{const f=fixture();try{const {matchId}=pair(f);f.call('ready',0,{matchId,deck});for(let i=0;i<2;i++){f.advance(10000);f.call('status',0);}f.advance(9999);assert.equal(f.call('status',0).status,'matched');f.advance(1);const result=f.call('status',0);assert.equal(result.status,'queued');assert.equal(result.reason,'requeued');assert.equal(result.queuedAt,f.clock());assert.equal(f.call('status',1).reason,'timeout');assert.throws(()=>f.call('ready',0,{matchId,deck}));f.call('join',2);f.advance(9999);assert.equal(f.call('status',0).status,'queued');f.advance(1);assert.equal(f.call('status',0).status,'matched');}finally{f.close();}});
test('cancel reparks opponent and stale cancellation cannot remove new ticket',()=>{const f=fixture();try{const {matchId}=pair(f);assert.equal(f.call('cancel',0,{matchId}).status,'idle');const opponent=f.call('status',1);assert.equal(opponent.status,'queued');assert.equal(opponent.reason,'requeued');assert.throws(()=>f.call('cancel',1,{matchId}));assert.equal(f.call('status',1).status,'queued');f.call('join',2);f.advance(10000);const fresh=f.call('status',1);assert.equal(fresh.status,'matched');assert.notEqual(fresh.matchId,matchId);assert.throws(()=>f.call('ready',1,{matchId,deck}));}finally{f.close();}});
test('inactive ready participant does not automatically requeue',()=>{const f=fixture();try{const {matchId}=pair(f);f.call('ready',0,{matchId,deck});f.advance(30000);assert.equal(f.call('status',0).status,'idle');assert.equal(f.call('status',1).status,'idle');}finally{f.close();}});
test('queue, preparation and resulting battle association survive real database reopen',()=>{const dir=mkdtempSync(path.join(tmpdir(),'artifact-mm-')),filename=path.join(dir,'db.sqlite');let store=new Store(filename),now=50000;const clock=()=>now;let maker=new Matchmaker(store,{clock});const a=store.identity(),b=store.identity();try{maker.request('join',a);store.close();store=new Store(filename);maker=new Matchmaker(store,{clock});assert.equal(maker.request('status',a).queuedAt,now);maker.request('join',b);now+=10000;const {matchId}=maker.request('status',a);maker.request('ready',a,{matchId,deck});store.close();store=new Store(filename);maker=new Matchmaker(store,{clock});assert.equal(maker.request('status',a).mineReady,true);const result=maker.request('ready',b,{matchId,deck});store.close();store=new Store(filename);maker=new Matchmaker(store,{clock});assert.equal(maker.request('status',a).code,result.code);assert.equal(maker.request('ready',b,{matchId,deck}).code,result.code);}finally{store.close();rmSync(dir,{recursive:true,force:true});}});

test('eligible queue pairs oldest first and respects distinct arrival times',()=>{const f=fixture();try{f.call('join',2);f.advance(1000);f.call('join',0);f.advance(1000);f.call('join',3);f.advance(1000);f.call('join',1);f.advance(9000);const oldest=f.call('status',2),second=f.call('status',0);assert.equal(oldest.matchId,second.matchId);assert.equal(f.call('status',3).status,'queued');assert.equal(f.call('status',1).status,'queued');f.advance(1000);assert.equal(f.call('status',3).matchId,f.call('status',1).matchId);}finally{f.close();}});

test('prepared snapshot reveals only own deck and an existing manual battle prevents a second match',()=>{const f=fixture();try{const {matchId}=pair(f);f.call('ready',0,{matchId,deck});f.reload();assert.deepEqual(f.call('status',0).ownDeck,{name:deck.name,heroes:deck.heroes,main:deck.main,items:deck.items});assert.equal(f.call('status',1).ownDeck,undefined);assert.equal(f.call('status',1).opponentDeck,undefined);const record=f.store.create(f.tokens[0]);const manual=new Match(record,r=>f.store.save(r));manual.join(f.tokens[2]);for(const seat of [0,1])manual.command(seat,{id:'manual'+seat,revision:manual.record.revision,action:'ready',args:{deck}});const response=f.call('ready',0,{matchId,deck});assert.equal(response.status,'battle');assert.equal(response.code,record.code);assert.equal(f.call('status',1).status,'queued');assert.equal(f.store.adminCounts().battle,1);}finally{f.close();}});
