'use strict';
const cards=require('../dist/cards.json');
const {Game,clone}=require('../dist/engine.js');
require('../dist/effects.js');
require('../dist/feedback.js');
class Match {
 constructor(record,save){this.record=record;this.save=save;this.game=new Game(cards);this.game.s=record.state;}
 join(token){let seat=this.record.seats.findIndex(s=>s?.token===token);if(seat>=0)return seat;if(this.record.status!=='lobby'||this.record.seats[1])throw Error('房间已满');seat=1;this.record.seats[seat]={token,deck:null,ready:false};this.persist();return seat;}
 persist(){this.record.state=this.game.s;this.save(this.record);}
 snapshot(seat,connected=[false,false],events=false,ack){const r=this.record,state=r.state?clone(r.state):null;if(state){delete state.deploymentPlan;if((seat===0||seat===1)&&state.phase==='deploy'&&r.deployPlans[seat]!==null)state.deploymentPlan=Object.fromEntries(r.deployPlans[seat].map(x=>[x.uid,x.lane]));if(!events)state.events=[];const spectator=seat!==0&&seat!==1;if(!spectator){state.mines=(state.mines||[]).filter(m=>m.owner===seat);for(const k of ['events','log'])state[k]=(state[k]||[]).filter(e=>e.secret===undefined||e.secret===seat);}for(let p=0;p<2;p++)if(spectator||p!==seat){state.players[p].hand=state.players[p].hand.map(h=>({uid:h.uid,k:'hidden',lock:h.lock||0}));state.players[p].shop=null;}for(let p=0;p<2;p++){state.players[p].deck=state.players[p].deck.map(()=>({k:'hidden'}));state.players[p].itemDeck=state.players[p].itemDeck.map(()=> 'hidden');}state.deckSpecs=state.deckSpecs.map((d,p)=>p===seat||r.status==='finished'?d:{name:d.name,heroes:d.heroes,main:[],items:[]});}return {code:r.code,revision:r.revision,seat,spectator:seat!==0&&seat!==1,status:r.status,players:r.seats.map((s,p)=>({occupied:!!s,ready:!!s?.ready,connected:!!connected[p],name:s?.deck?.name||('玩家 '+(p+1))})),state,shopReady:r.shopReady,deployReady:r.deployPlans.map(p=>p!==null),...(ack?{ack}:{})};}
 command(seat,message){const r=this.record;if(seat!==0&&seat!==1)throw Error('观战模式无法操作对局');if(!r.seats[seat])throw Error('无效席位');if(!message||typeof message.id!=='string'||message.id.length<1||message.id.length>100)throw Error('操作编号无效');if(r.processed[seat].includes(message.id))return {duplicate:true};if(message.revision!==r.revision)throw Error('棋局已更新，请重试');const backup=clone(r);try{this.apply(seat,message.action,message.args||{});r.revision++;r.processed[seat].push(message.id);r.processed[seat]=r.processed[seat].slice(-256);if(this.game.s?.winner!==null&&this.game.s?.winner!==undefined)r.status='finished';this.persist();return {duplicate:false};}catch(e){this.record=backup;this.game.s=backup.state;throw e;}}
 apply(p,action,a){const r=this.record,g=this.game;
  if(action==='ready'||action==='unready'){if(r.status!=='lobby')throw Error('对局已经开始');if(action==='unready'){r.seats[p].ready=false;return;}if(!a.deck||a.deck.main?.length>200||a.deck.items?.length>100)throw Error('构筑格式不正确');const errors=g.validateDeck(a.deck);if(errors.length)throw Error(errors.join('；'));r.seats[p].deck={name:String(a.deck.name||'自定义构筑').slice(0,80),heroes:[...a.deck.heroes],main:[...a.deck.main],items:[...a.deck.items]};r.seats[p].ready=true;if(r.seats.every(s=>s?.ready)){g.newGame(r.seats[0].deck,r.seats[1].deck);r.status='battle';}return;}
  if(r.status!=='battle')throw Error('当前没有进行中的对局');g.s.events=[];
  if(action==='concede'||action==='surrender'){g.s.winner=1-p;g.s.phase='ended';g.emit('victory',`${p?'夜魇':'天辉'}认输`,{winner:1-p});return;}
  if(['play','activate','pass'].includes(action)){if(g.s.phase!=='action'||g.s.turn!==p)throw Error('尚未轮到你行动');if(action==='pass')g.pass(p);else if(action==='play')g.play(p,a.handId,a.targets||[]);else g.activate(p,a.sourceId??a.id,a.key,a.targets||[]);return;}
  if(['buy','hold','shopReady','finishShop'].includes(action)){if(g.s.phase!=='shop')throw Error('现在不是购物阶段');if(r.shopReady[p])throw Error('你已结束购物，等待对方确认');if(action==='buy')g.buy(p,a.slot);else if(action==='hold')g.hold(p);else{r.shopReady[p]=true;if(r.shopReady.every(Boolean)){g.startRound();r.shopReady=[false,false];r.deployPlans=[null,null];}}return;}
  if(action==='deployReady'||action==='deploy'){if(g.s.phase!=='deploy')throw Error('现在不是部署阶段');if(r.deployPlans[p]!==null)throw Error('分路已确认，等待对方');const ready=g.ready(p),list=a.assignments;if(!Array.isArray(list)||list.length!==ready.length||new Set(list.map(x=>x.uid)).size!==list.length)throw Error('请安排全部待命英雄');for(const assignment of list){if(!ready.some(u=>u.uid===assignment.uid)||!Number.isInteger(assignment.lane)||assignment.lane<0||assignment.lane>2||assignment.pos!=null&&(!Number.isInteger(assignment.pos)||assignment.pos<0||assignment.pos>99))throw Error('无效英雄分路');}const before=clone(g.s);try{for(const x of list)g.deploy(x.uid,x.lane,x.pos??null);}finally{g.s=before;}r.deployPlans[p]=clone(list);if(r.deployPlans.every(v=>v!==null)){for(const plan of r.deployPlans)for(const x of plan)g.deploy(x.uid,x.lane,x.pos??null);g.finishDeployment();r.deployPlans=[null,null];}return;}
  throw Error('不支持的操作');
 }
}
module.exports={Match};
