'use strict';
const assert=require('node:assert/strict');
const {Store}=require('./store.cjs');
const {Match}=require('./match.cjs');
require('../dist/decks.js');
const store=new Store(':memory:');let counter=0,passed=0;
function fixture(){const a=store.identity(),b=store.identity(),r=store.create(a),m=new Match(r,x=>store.save(x));m.join(b);const send=(p,action,args={})=>m.command(p,{id:String(++counter),revision:m.record.revision,action,args});send(0,'ready',{deck:global.ARTIFACT_DECKS[0]});send(1,'ready',{deck:global.ARTIFACT_DECKS[1]});return {m,send,a,b};}
function test(name,fn){fn();console.log('PASS',name);passed++;}
test('invalid turn and replay never advance combat twice',()=>{const {m}=fixture(),id='once';assert.throws(()=>m.command(1,{id:'bad',revision:m.record.revision,action:'pass'}));const rev=m.record.revision;m.command(0,{id,revision:rev,action:'pass'});const state=JSON.stringify(m.game.s);assert.equal(m.command(0,{id,revision:rev,action:'pass'}).duplicate,true);assert.equal(JSON.stringify(m.game.s),state);});
test('one shopper cannot advance round and purchases do not attack',()=>{const {m,send}=fixture();m.game.s.phase='shop';m.game.openShop();m.game.s.players[0].gold=30;m.persist();const hp=m.game.s.units.map(u=>u.damage);send(0,'buy',{slot:'consumable'});assert.deepEqual(m.game.s.units.map(u=>u.damage),hp);send(0,'shopReady');assert.equal(m.game.s.round,1);assert.throws(()=>send(0,'buy',{slot:'deck'}));send(1,'shopReady');assert.equal(m.game.s.round,2);assert.equal(m.game.s.phase,'deploy');});
test('deployment is hidden, validated and jointly committed',()=>{const {m,send}=fixture();m.game.s.phase='shop';m.game.openShop();send(0,'shopReady');send(1,'shopReady');const first=m.game.ready(0)[0],other=m.game.ready(1)[0];assert(first&&other);assert.throws(()=>send(0,'deployReady',{assignments:[{uid:other.uid,lane:0}]}));send(0,'deployReady',{assignments:[{uid:first.uid,lane:2}]});assert.equal(m.game.get(first.uid).alive,false);assert.equal(m.snapshot(1).state.units.find(u=>u.uid===first.uid).alive,false);send(1,'deployReady',{assignments:[{uid:other.uid,lane:1}]});assert.equal(m.game.get(first.uid).lane,2);assert.equal(m.game.get(other.uid).lane,1);assert.equal(m.game.s.phase,'action');});
test('seat identity and room state survive a fresh Match instance',()=>{const {m,send,a,b}=fixture();send(0,'pass');const reloaded=new Match(store.load(m.record.code),x=>store.save(x));assert.equal(reloaded.join(a),0);assert.equal(reloaded.join(b),1);assert.throws(()=>reloaded.join(store.identity()));assert.deepEqual(reloaded.game.s,m.game.s);assert.equal(reloaded.snapshot(0).state.events.length,0);assert(reloaded.snapshot(0).state.players[1].hand.every(h=>h.k==='hidden'));});
test('failed deployment leaves random seed and state unchanged',()=>{const {m,send}=fixture();m.game.s.phase='shop';m.game.openShop();send(0,'shopReady');send(1,'shopReady');const before=JSON.stringify(m.game.s),u=m.game.ready(0)[0],occupied=m.game.all(0,0)[0];assert.throws(()=>send(0,'deployReady',{assignments:[{uid:u.uid,lane:0,pos:occupied.pos}]}));assert.equal(JSON.stringify(m.game.s),before);});
test('concession uses original end-screen phase and persists winner',()=>{const {m,send}=fixture();send(1,'concede');assert.equal(m.record.status,'finished');assert.equal(m.game.s.phase,'ended');assert.equal(store.load(m.record.code).state.winner,0);assert.throws(()=>send(0,'pass'));});
test('cast snapshots retain feedback outcomes and reconnection drops effects',()=>{const {m,send}=fixture();const u=m.game.all(1,0)[0],h={uid:m.game.id(),k:'no_accident',lock:0};m.game.s.players[0].hand.push(h);m.game.spawn('phantom_assassin',0,0);m.persist();send(0,'play',{handId:h.uid,targets:[u.uid]});const events=m.snapshot(0,[true,true],true).state.events,cast=events.find(e=>e.type==='card');assert(cast.targets.some(t=>t.uid===u.uid));assert(cast.outcomes.length);assert.equal(m.snapshot(0).state.events.length,0);});
test('confirmed deployment restores only the requesting seat plan after reload',()=>{for(const seat of [0,1]){const {m,send}=fixture();m.game.s.phase='shop';m.game.openShop();send(0,'shopReady');send(1,'shopReady');const u=m.game.ready(seat)[0];send(seat,'deployReady',{assignments:[{uid:u.uid,lane:2}]});const reloaded=new Match(store.load(m.record.code),x=>store.save(x));assert.deepEqual(reloaded.snapshot(seat).state.deploymentPlan,{[u.uid]:2});assert.equal(reloaded.snapshot(1-seat).state.deploymentPlan,undefined);assert.equal(reloaded.game.s.deploymentPlan,undefined);assert.equal(reloaded.snapshot(1-seat).state.units.find(x=>x.uid===u.uid).alive,false);}});
store.close();console.log(`${passed} online room logic checks passed`);
